### ISSUE TITLE
Restarted KEB didn't resume unfinished update operation

### ISSUE THREAD

**Issue by wozniakjan** [kyma-project/control-plane#1058]
**Description**
When testing https://github.com/kyma-project/control-plane/pull/920, I stumbled upon a situation, where KEB was restarted in the middle of processing an update operation. It never picked up the operation and I had to delete it manually from operations DB to unblock changing the instance. Provisioner and gardener have finished their processing successfully.

```
provisioner=> select id, type, state, message, cluster_id, stage from operation where cluster_id = '9bbe4b6e-944f-44c5-993a-5da9b6f3a59d';
                  id                  |     type      |   state   |       message       |              cluster_id              |  stage
--------------------------------------+---------------+-----------+---------------------+--------------------------------------+----------
 50e3ea98-568b-41e7-9d9a-6d3e0f70d40a | PROVISION     | SUCCEEDED | Operation succeeded | 9bbe4b6e-944f-44c5-993a-5da9b6f3a59d | Finished
 d143215d-6c6a-4564-ae6c-f5faf00336f2 | UPGRADE_SHOOT | SUCCEEDED | Operation succeeded | 9bbe4b6e-944f-44c5-993a-5da9b6f3a59d | Finished
```

```
broker=> select instance_id, type, state from operations where instance_id='739C5BC4-27F0-4008-9786-0EF469D4FC0C';
             instance_id              |   type    |    state
--------------------------------------+-----------+-------------
 739C5BC4-27F0-4008-9786-0EF469D4FC0C | update    | in progress
 739C5BC4-27F0-4008-9786-0EF469D4FC0C | provision | succeeded
```

There also seems to be slightly larger delay in KEB to pick up state from provisioner and gardener even for standard scenarios. Updating autoscaler params in gardener and provisioner takes seconds at most, but KEB takes frequently few minutes to propagate the status.

**Expected result**

Restarted KEB should always resume processing all unfinished operations

**Actual result**

KEB didn't resume one unfinished update operation

**Steps to reproduce**

Restart KEB when there is an update operation in progress

**Troubleshooting**

**Comment by piotrmiskiewicz** [comment]
related to https://github.tools.sap/kyma/backlog/issues/2032

**Comment by ksputo** [comment]
https://github.com/kyma-project/control-plane/pull/1109/files
