### ISSUE TITLE
KEB should wait for reconciler deletion

### ISSUE THREAD

**Issue by ksputo** [kyma-project/control-plane#1080]
**Description**
Currently KEB does not wait for reconciler deletion and the deprovisioning process is not adjusted to work with reconciler yet.

**Reasons**
We already use reconciler for spinning up Kyma 2.0 clusters when provisioning, but the deprovisioning part is not implemented yet.

**Attachments**

**Comment by pbochynski** [comment]
PR: https://github.com/kyma-project/control-plane/pull/1088
