### ISSUE TITLE
Hide kubeconfig from the json output from reconciliation info command

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/control-plane#1083]
**Description**

We shouldn't show a kubeconfig file as part of `kcp rc info -c shoot-name` command.

**Reasons**

There is a separated command and API for that that purpose. It is easier to manage access permissions if commands are not mixing few responsibilities

**Attachments**

```
kcp reconciliations info -i 4fa722d5-83cb-4495-8a9e-4b80ba4cd476--a61e5197-20f3-4e5d-b728-94751e6c54eb --config ~/.kcp/kcp-cli_config-dev.yaml -o json
{
  "cluster": {
    "kubeconfig": "..........",
    "kymaConfig": {
      "administrators": [
        "....."
      ],
      "components": [],
      "profile": "Production",
      "version": "2.0.0-rc4"
    },
    "metadata": {
      "globalAccountID": "......",
      "instanceID": ".......",
      "serviceID": ".......",
      "servicePlanID": ".......",
      "shootName": "shoot-name",
      "subAccountID": "......"
    },
    "runtimeID": ".....",
    
  },
  "operations": [
    {
    ...
    }
   ]
}
    ```

**Comment by dbadura** [comment]
I think that this endpoint shouldn't return kubeconfig.

There should be special endpoint to fetch kubeconfig.

**Comment by kwiatekus** [comment]
We should rework the PR so that we keep kyma config as discussed here
https://github.com/kyma-incubator/reconciler/issues/433#issuecomment-972746831

**Comment by kwiatekus** [comment]
changes in the reconciler API applied -> https://github.com/kyma-incubator/reconciler/pull/427
changes in CLI in progress -> https://github.com/kyma-project/control-plane/pull/1114

**Comment by kwiatekus** [comment]
Everything merged.
Deployment of that is still pending due to audit-log pvc config problem
https://github.com/kyma-project/control-plane/pull/1137
Lets keep open until its deployed to dev landscape
