### ISSUE TITLE
When upgrading to 2.0 replace existing overrides with new ones

### ISSUE THREAD

**Issue by PK85** [kyma-project/control-plane#1095]
**Description**

Right now we have duplicated overrides keys when KEB calls reconciler.  They come from previous provisioning runs and when upgrading. Could happen that the same key has updated value and reconciler can take the old one.

**Reasons**

Potential Kyma misconfigurations could happen now.

**AC**

- when upgrading to 2.0 replace existing overrides with new ones

**Comment by ksputo** [comment]
hotfixed in: https://github.com/kyma-project/control-plane/pull/1112

to do:
- [ ] improve test coverage of those functionalities
