### ISSUE TITLE
Enable x-envoy-external-address header in istio configuration.

### ISSUE THREAD

**Issue by moelsayed** [kyma-project/control-plane#1121]
**Description**
For logging proposes, the mothership reconciler needs to have access to the client IP for the API requests. Istio needs to be configured to populate the `x-envoy-external-address` with the correct value of the client IP.

**Reasons**
- Logging requirements. 

**Attachments**
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-envoy-external-address

**Comment by strekm** [comment]
i think it become invalid since we are switching to lifecycle manager
