### ISSUE TITLE
KEB update queue is inconsistent at processing operations

### ISSUE THREAD

**Issue by wozniakjan** [kyma-project/control-plane#1122]
**Description**

The update queue has odd behaviour when processing update operations. An operation as observed in BTP cockpit shows "Failed" without any explanation, but in KEB database it shows 
```
{"state":"succeeded","description":"update in progress"}
```
Previously it also showed no state at all with a description `update in progress`, which likely confused BTP cockpit and it eventually considered the operation as failed.

**Expected result**

consistent and deterministic processing of update operations to always contain valid state as well as matching description.

**Actual result**

inconsistent and non-deterministic update operations processing with mismatching description.

**Steps to reproduce**

update an SKR from BTP cockpit.

**Troubleshooting**

**Comment by szwedm** [comment]
I thoroughly checked KEB's behavior while it's processing the update queue. Everything works fine, just an update of operation description on success was missing. I addressed this in the following PR:
https://github.com/kyma-project/control-plane/pull/1162

**Comment by szwedm** [comment]
BTP Cockpit does not refresh update status until user reloads a page. Even when KEB and Provisioner are done with processing update operation and mark it as succeeded, BTP Cockpit displays `Processing` status. After some time BTP Cockpit session expires, a pop-up window to reload a page appears and user is required to do so. After page reload, update status in BTP Cockpit is green.

**Comment by wozniakjan** [comment]
thanks @szwedm for thorough investigation. I guess the most problematic part when BTP Cockpit was showing "failed" despite KEB reporting "success" has already been fixed on the other side of the fence. I think there might be still some room for UX improvement on the BTP Cockpit side but that is not in scope of this issue.

I vote for successful close of this one.

**Comment by wozniakjan** [comment]
@szwedm never mind, I guess I was wrong with the stability of this. @PK85 found another instance of our update queue manager to not be as robust as we hoped, copying his comments here for better visibility:

> Something is still messed up on our side. I'provisioned canary azure 2.0 in our kyma-integration GA and in BTP status "in progress" in a forever mode. Then checked did investigation on our side:

```
https://kyma-env-broker.{{ host  }}/oauth/v2/service_instances/516C9308-DDF3-4D1C-A1A7-E14EB80724FF/last_operation
```
> returns:
```
{
	"state": "in progress",
	"description": "update in progress"
}
```
> Gardener was updated really fast and nodes were scaled up.

> Next: 
```
kcp runtimes -c c-713d7b2 -o json
```
> and:
```
  "data": [
    {
      "instanceID": "516C9308-DDF3-4D1C-A1A7-E14EB80724FF",
      "runtimeID": "36bdb89e-d62b-440c-9dc7-a9f2e5f7b376",
      "globalAccountID": "d4037436-f01a-4adc-aa2b-52836f459bfe",
      "subAccountID": "30a620f8-cf71-4a67-9f67-38343fe4e38e",
      "region": "westeurope",
      "subAccountRegion": "cf-eu10-canary",
      "shootName": "c-713d7b2",
      "serviceClassID": "47c9dcbf-ff30-448e-ab36-d3bad66ba281",
      "serviceClassName": "kymaruntime",
      "servicePlanID": "4deee563-e5ec-4731-b9b1-53b42d855f0c",
      "servicePlanName": "azure",
      "provider": "Azure",
      "status": {
        "createdAt": "2021-12-10T10:19:27.832071Z",
        "modifiedAt": "2021-12-13T21:51:04.915981Z",
        "state": "updating",
        "update": {
          "data": [
            {
              "state": "in progress",
              "description": "update in progress",
              "createdAt": "2021-12-13T21:51:04.412161Z",
              "operationID": "022c887a-cd66-4b91-9597-b20633b1e4d6"
            }
          ],
          "totalCount": 1,
          "count": 1
        }
      },
      "userID": "piotr.kopczynski@sap.com",
      "avsInternalEvaluationID": 156095257
    }
  ],
  "count": 1,
  "totalCount": 1
```

**Comment by wozniakjan** [comment]
fwiw, it looks like KEB is sometimes just really slow at processing the update operation because today it is marked as successfully processed

```
$ kcp runtime -c c-713d7b2 -ojson
```
```json
{
  "data": [
    {
      "instanceID": "516C9308-DDF3-4D1C-A1A7-E14EB80724FF",
      "runtimeID": "36bdb89e-d62b-440c-9dc7-a9f2e5f7b376",
      "globalAccountID": "d4037436-f01a-4adc-aa2b-52836f459bfe",
      "subAccountID": "30a620f8-cf71-4a67-9f67-38343fe4e38e",
      "region": "westeurope",
      "subAccountRegion": "cf-eu10-canary",
      "shootName": "c-713d7b2",
      "serviceClassID": "47c9dcbf-ff30-448e-ab36-d3bad66ba281",
      "serviceClassName": "kymaruntime",
      "servicePlanID": "4deee563-e5ec-4731-b9b1-53b42d855f0c",
      "servicePlanName": "azure",
      "provider": "Azure",
      "status": {
        "createdAt": "2021-12-10T10:19:27.832071Z",
        "modifiedAt": "2021-12-13T21:51:04.915981Z",
        "provisioning": {
          "state": "succeeded",
          "description": "Operation created",
          "createdAt": "2021-12-10T10:19:27.826292Z",
          "operationID": "54169518-7c6e-4275-917b-e8ab1301f52a"
        },
        "upgradingKyma": {
          "data": null,
          "totalCount": 0,
          "count": 0
        },
        "upgradingCluster": {
          "data": null,
          "totalCount": 0,
          "count": 0
        },
        "suspension": {
          "data": null,
          "totalCount": 0,
          "count": 0
        },
        "unsuspension": {
          "data": null,
          "totalCount": 0,
          "count": 0
        }
      },
      "userID": "piotr.kopczynski@sap.com"
    }
  ],
  "count": 1,
  "totalCount": 1
}
```

I suppose a good starting point would be looking at prometheus metrics for how long it takes to process various operations (or add some if they don't exist yet)

**Comment by wozniakjan** [comment]
Digging through the logs didn't help me to discover anything useful.
* It looks like provisioner took ~6 minutes to poll gardener for success on the operation `80e8602b-0f62-4a5e-94ac-89079793bd42`, 
  * started at Dec 13, 2021 @ 22:51:05.183
  * finished at Dec 13, 2021 @ 22:57:50.854 
  * [logs](https://kibana-sf-558ad93f-5db5-4608-8cbf-061dac3471ff.cls-02.cloud.logs.services.eu10.hana.ondemand.com/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-24h,to:now))&_a=(columns:!(_source),filters:!(),index:'14924510-9c02-11eb-8771-5dea5972a9ee',interval:auto,query:(language:kuery,query:%2280e8602b-0f62-4a5e-94ac-89079793bd42%22),sort:!()))
* KEB processing of that operation seems to have halted
  * it called provisioner at Dec 13, 2021 @ 22:51:05.180 but last log message in KEB mentioning this update `operation_id=022c887a-cd66-4b91-9597-b20633b1e4d6` is Dec 13, 2021 @ 22:51:05.199, after that KEB never reuques this operation
  * [logs](https://kibana-sf-558ad93f-5db5-4608-8cbf-061dac3471ff.cls-02.cloud.logs.services.eu10.hana.ondemand.com/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-24h,to:now))&_a=(columns:!(_source),filters:!(),index:'14924510-9c02-11eb-8771-5dea5972a9ee',interval:auto,query:(language:kuery,query:'%22022c887a-cd66-4b91-9597-b20633b1e4d6%22%20AND%20kubernetes.container_name:%20kyma-environment-broker'),sort:!()))


I have tried to reproduce the case and I couldn't get the exact same behaviour.

**Comment by szwedm** [comment]
@wozniakjan thanks for the information. We might have a bug in the update queue that will be really hard to spot. It's strange that KEB dropped the update operation, leaving it with 'in progress' state. I wonder if that could happen when KEB pods are terminated while the operation has not been fully processed.

**Comment by wozniakjan** [comment]
> KEB pods are terminated while the operation has not been fully processed.

that was also my suspicion but at the moment of writing this, KEB has been up for over 3 days without being terminated, so it is probably something else. For me, really hard to debug, I think we may want to implement better and more detailed tracking for each operation at the cost of performance.

**Comment by wozniakjan** [comment]
update: there are actually two bugs both introduced by my PR #825
1) the update queue will always try to check reconciliation status for kyma2.0. In this case, the status was failing because reconciliation had some bugs, but for min/max updates we don't need to check that and can pronounce cluster healthy despite reconciliation failing
2) the operation needs to be explicitly marked as "failed", and it wasn't implemented that way.

I will submit a PR shortly addressing at least some portion of the shortcomings.
