### ISSUE TITLE
HAP supporting multiple Gardener projects

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/control-plane#115]
**Description**

In the current state, there is only one Gardener project that is supported by HAP. For security and separation reasons we would like to make HAP able to handle multiple Gardener projects (probably determined by the plan that is used to create an instance). The best solution would be to make that configurable - the list of Gardener projects would be provided and then HAP could manage subscriptions in any of them (depending on which should be used for the given plan).

**Acceptance Criteria**
- HAP accepts multiple Gardener projects
- The list of Gardener projects is passed via KEB configuration
- Depending on the plan proper Gardener project is chosen for fetching an available subscription

**Comment by ebensom** [comment]
This would also impact

1. metris
2. Different gardener credentials per project for KEB & provisioner
2. Orchestration runtime resolver
3. Gardener usage data exporter

Also it introduces a magnitude of complexity in operations. 

Do we really need separate project per plan? Or the real requiremwnt is more about separation of trial vs regular clusters?
The isolation of clusters by using different provider credentials is good enough IMO, and the logical grouping and ability being to manage all SKRs in a landscape (e.g. production) within a gardener project is quite important in many operations cases.
