### ISSUE TITLE
KEB status updatedAT is not refreshed properly

### ISSUE THREAD

**Issue by PK85** [kyma-project/control-plane#1171]
**Expected result**

- make updatedAT up to date on rutnimes and cld endpoints

**Steps to reproduce**

Provision Kyma and see updatedAT value.

**Example**

8 sec and reconiciler failed after 30 minutes of retries.
```
  {
    "runtimeId": "179dc682-e0d8-44ef-aad2-c959e9862f95",
    "globalAccountId": "e449f875-b5b2-4485-b7c0-98725c0571bf",
    "subaccountId": "3af623d8-034c-4c00-a649-95446014fcc5",
    "subaccountRegion": "cf-eu10",
    "serviceInstanceId": "ee202cd5-b707-44fe-b556-22ed33097b05",
    "serviceClassId": "47c9dcbf-ff30-448e-ab36-d3bad66ba281",
    "serviceClassName": "kymaruntime",
    "servicePlanId": "5cb3d976-b85c-42ea-a636-79cadda109a9",
    "servicePlanName": "preview",
    "status": {
      "createdAt": "2021-10-11T15:42:52.94139Z",
      "updatedAt": "2021-10-11T15:43:00.292993Z",
      "provisioning": {
        "state": "failed",
        "description": "Operation created : Reconciler failed"
      }
    }
  },
```

**Comment by PK85** [comment]
Another example:
```
{
    “runtimeId”: “26f9ffbd-5989-4918-ba94-d0e1dfa9934d”,
    “globalAccountId”: “2358e708-68f0-4af0-94b6-cf4e8407aff8",
    “subaccountId”: “e97a29c9-18f6-4c75-8ef3-4419c6ddee63",
    “subaccountRegion”: “cf-us10-staging”,
    “serviceInstanceId”: “59AE1111-81CB-407D-BAD4-B93259222E1D”,
    “serviceClassId”: “47c9dcbf-ff30-448e-ab36-d3bad66ba281",
    “serviceClassName”: “kymaruntime”,
    “servicePlanId”: “5cb3d976-b85c-42ea-a636-79cadda109a9",
    “servicePlanName”: “preview”,
    “status”: {
      “createdAt”: “2021-12-06T14:07:17.291216Z”,
      “updatedAt”: “2021-12-06T14:07:18.741203Z”,
      “provisioning”: {
        “state”: “succeeded”,
        “description”: “Operation created”
      }
    }
  },
```
Kyma installed in 1 sec :)

**Comment by ksputo** [comment]
`updatedAt` (for `info/runtime`) and `modifiedAt` (for `/runtimes`) values are taken from Instance, which is not updated when process finishes (success/failure) - we only update the corresponding Operation data. The Instance data is only updated when suspending/unsuspending, on instance update (for example autoscaler parameters change), on provisioning after getting runtimeID from provisioner. For details, see all usages of
https://github.com/kyma-project/control-plane/blob/1e307c89ca0d37f1b65ec979de7225a3c2b5a3e1/components/kyma-environment-broker/internal/storage/ext.go#L15

Possible solutions are:
- calling Update method on each process failure (when OperationFailed method is called) or success (OperationSucceeded or UpdateOperation when all steps finished) without any data changes - `updatedAt` timestamp will be overwritten here: 
https://github.com/kyma-project/control-plane/blob/1e307c89ca0d37f1b65ec979de7225a3c2b5a3e1/components/kyma-environment-broker/internal/storage/postsql/write.go#L77

- change the presentation layer to use `updatedAt` timestamp from latest operation for given instance
- extend operations data in the payload to include also `updatedAt` timestamp (it already has `createdAt` on `/runtimes` endpoint, for `info/runtimes` there's no such data printed) like this:
```
        "provisioning": {
          "state": "succeeded",
          "description": "Operation created",
          "createdAt": "2021-10-29T14:42:01.810446Z",
          "updatedAt": "2021-10-29T15:42:01.810446Z",
          "operationID": "e7c12049-2482-4bd4-8041-05b7e4b7dd0f"
        },
```
