### ISSUE TITLE
Upgrading Kyma instances from Kyma Control Plane

### ISSUE THREAD

**Issue by PK85** [kyma-project/control-plane#118]
**Description**

This issue is the minimum viable product in the Kyma upgrade topic from the central place, namely the Kyma Environment Broker. Goal is to allow operator to do bulk Kyma upgrades on all Kyma's managed by KEB.

**Solution Concept**

The idea is to implement an orchestration layer within Kyma Environment Broker which would comprise of:
1) process/upgrade/kyma package, which is responsible for the Kyma release upgrades/reconfigurations use-case. It implements the  UpgradeKymaManager which performs and persists the given Kyma upgrade operation specific to a runtime instance.
2) orchestration package which is a common library aiding the implementation of orchestration managers. It contains RuntimeResolver for resolving target configurations to runtimes, and different OrchestrationStrategy implementations which performs orchestration according to encapsulated strategies.
3) orchestration/kyma package, which incorporates:
  3.1) REST API endpoint and handler which accepts triggering "bulk" Kyma upgrades on SKRs. The handler creates Orchestration persisted object, and adds it to a Queue with UpgradeKymaOrchestration executor for processing
  3.2) the UpgradeKymaOrchestration.Execute(orchestrationID string) orchestrates the kyma upgrades using UpgradeKymaManager on the resolved targets, according to the specified orchestration strategy

**Reasons**

In case of many Kyma clusters that story will simplify Kyma upgrades management.

**AC**
- prepare endpoints basepaths and names for below API requirements
- make Orchestration Trigger API "POST /orchestration/kyma/upgrade" really simple for now:
  - support to upgrade one kyma instance
  - ~~support to upgrade all kyma instances~~
  - support dry-run option that will show number of Kyma instances that will be updated
- provide Orchestration Status API "GET /orchestration/kyma/upgrade?operation_id=47c9dcbf-ff30-448e-ab36-d3bad66ba281" for given operation
- provide Orchestration Status API "GET /orchestration/kyma/upgrade for all runtimes statuses
 - example response nested runtime entity:
```
      "instanceID": "054ac2c2-318f-45dd-855c-eee41513d40d",
      "runtimeID": "44a57cbd-5271-4d68-8cf9-9dabbb9f1c44",
      "globalAccountID": "",
      "subAccountID": "",
      "clusterURL": "c-084befc"
      "operationID": "f683e77c-7d24-4aee-91af-4208bcfc480f",
      "serviceClassId": ...,
      "servicePlanId": ...,
      "serviceClassName": ...,
      "servicePlanName": ...,
      "kymaVersion": ...,
      "provisioningStatus": ...,
      "deprovisioningStatus": ...,
      "upgradeState": "InProgress" / "Pending" / "Succeeded" / "Failed"
```
- we support only one SKR version overrides in the pipeline (that means when new Kyma is released, besides KEB Kyma version operators needs to adjust overrides if needed)
- KEB supports two new scopes: broker_upgrade:write and broker_upgrade:read and client credentials

**Out of scope, planned for next iterations**
- bulk update (we support only upgrade for one SKR instance, of coure API could be called many times and operator can simulate bulk operation)
- Upgrade from KEB do not rerun steps (only new upgrade_runtime step is called)

**Attachements**
- Provisioner docs: https://github.com/kyma-project/control-plane/blob/master/docs/internal/runtime-upgrade.md

**Comment by PK85** [comment]
topics:
- KEB works with static overrides per Kyma version for provisioner
- KEB takes into account steps changes, new steps
- could we send always all overrides? Or we need to send only new ones. Jan: every module has own config map + one for global overrides
- prepare procedure where manual Kyma migration is required
- Upgrade API - custom API

**Comment by ebensom** [comment]
FYI the solution concept doc: https://cxwiki.sap.com/pages/viewpage.action?spaceKey=ysf&title=Orchestration+of+SKR+Changes#OrchestrationofSKRChanges-SolutionConcept
