### ISSUE TITLE
KEB: AvS client does not handle errors properly

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/control-plane#119]
**Description**

When the communication with the AvS system has a problem, the AvS client has "nil pointer dereference" error.
The bug can be reproduced with a unit test:
```
func TestClient_RemoveReferenceFromParentEvalError(t *testing.T) {
	// Given
	server := newServer(t)
	mockServer := fixHTTPServer(server)
	client, err := NewClient(context.TODO(), Config{
		OauthTokenEndpoint: fmt.Sprintf("%s/oauth/token", mockServer.URL),
		ApiEndpoint:        fmt.Sprintf("%s/api/v2/evaluationmetadata", "http://not-existing"),
		ParentId:           parentEvaluationID,
	})
	assert.NoError(t, err)

	// When
	err = client.RemoveReferenceFromParentEval(evaluationID)
}
```

Additionally, we can see in logs the following entry:
```
time="2020-08-10T10:21:28Z" level=error msg="panic error from process: runtime error: invalid memory address or nil pointer dereference"
```
Try to log as json and put there operation/instance ids. Let's try to reuse dedicated logger used by steps (if possible).

**Expected result**

When communication with AvS is broken, step should be repeated. In case of a panic, we should see more readable log entry.

**Comment by polskikiel** [comment]
PR with the fix was merged
