### ISSUE TITLE
Align reconciler contract in KEB

### ISSUE THREAD

**Issue by ksputo** [kyma-project/control-plane#1195]
**Description**
Reconciler introduces new cluster status `reconcile_error_retryable` here:https://github.com/kyma-incubator/reconciler/pull/531
which is currently not supported in KEB. Getting this error result in
```
{"level":"error","msg":"Error from process: unknown cluster status: reconcile_error_retryable"
```

**AC**
KEB should handle the new cluster status properly.
- Check the cluster status again when getting `reconcile_error_retryable` - check with reconciler team when the error is exactly thrown

**Stretch**
- Get rid of `contract.go` in KEB, import the structs directly from reconciler's `pkg`

**Attachments**

**Comment by ralikio** [comment]
Implementation in https://github.com/kyma-project/control-plane/pull/1222.
