### ISSUE TITLE
KEB to use default overridesVersion when provisioning SKR for PR-xxx

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/control-plane#1252]
**Description**

I am working on a prow job (pre-submit ) to provision SKR for the PRs, and run some tests. 

Right now, in the KEB REST API to provision SKR, if we specify a PR in `kymaVersion: PR-xxx`, then we need to also specify the `overridesVersion`, otherwise it fails.

Since, in the prow job its hard to figure out the latest `overridesVersion` available, it would be great if KEB automatically use the default overrides version for `kymaVersion: PR-xxx`, if the `overridesVersion` parameter is not specified in the rest call.

**Comment by piotrmiskiewicz** [comment]
@mfaizanse  Be aware that the main branch could require different overrides than the last released kyma and in such case the job fails.

**Comment by mfaizanse** [comment]
In that case, we can manually provide the compatible `overridesVersion`. But in most of the cases the latest `overridesVersion` would be fine with main.

**Comment by PK85** [comment]
yes, that thing needs to be provided explicitly cause overrides for that PR version are not defined.
