### ISSUE TITLE
All runtime states should contain kyma version in a single non-encrypted column

### ISSUE THREAD

**Issue by wozniakjan** [kyma-project/control-plane#1264]
**Description**

Currently, only some runtime states contain kyma version in a database column that is not encrypted, operations regarding kyma 2.x store this information in an encrypted column of runtime state.
https://github.com/kyma-project/control-plane/pull/825/files#r759410773

**Reasons**
It would be very useful to retroactively populate the existing operations and put the kyma version to a non-encrypted column that makes querying this information a lot easier. Also changing KEB code to always put kyma version if it is being upgraded or relevant for the operation.

**Attachments**

this would be an optimization for current implementation https://github.com/kyma-project/control-plane/pull/825/files#r759410773

**Comment by szwedm** [comment]
Two actions should be taken to keep record of Kyma version in RuntimeState for 2.x:
1. Code the logic in KEB for storing Kyma version in KymaVersion field when dealing with ops related to 2.x.
2. Create a script that will update existing records in DB where Kyma version field is empty.

I am currently working on the 1st point, will keep posting updates.

**Comment by szwedm** [comment]
> 1. Code the logic in KEB for storing Kyma version in KymaVersion field when dealing with ops related to 2.x.
Implemented: [PR](https://github.com/kyma-project/control-plane/pull/1267)

**Comment by wozniakjan** [comment]
> Two actions should be taken to keep record of Kyma version in RuntimeState for 2.x:

Can you please either add a follow-up issue or 3. point here described in https://github.com/kyma-project/control-plane/pull/825/files#r759410773. The query currently fetches N latest runtime states, decrypts them one by one and picks the latest one that has some kyma version populated. With having every relevant runtime state containing kyma version non-encrypted, we can optimize the query to fetch just the latest.

**Comment by szwedm** [comment]
> > Two actions should be taken to keep record of Kyma version in RuntimeState for 2.x:
> 
> Can you please either add a follow-up issue or 3. point here described in https://github.com/kyma-project/control-plane/pull/825/files#r759410773. The query currently fetches N latest runtime states, decrypts them one by one and picks the latest one that has some kyma version populated. With having every relevant runtime state containing kyma version non-encrypted, we can optimize the query to fetch just the latest.

Let's make this point no. 3 since it's all connected. The list is as follows:

1. Code the logic in KEB for storing Kyma version in KymaVersion field when dealing with ops related to 2.x. - [done](https://github.com/kyma-project/control-plane/pull/1267)
2. Create a script that will update existing records in DB where Kyma version field is empty - in progress
3. Optimize the following [query](https://github.com/kyma-project/control-plane/pull/825/files#r759410773) to fetch the latest runtime state with Kyma version

**Comment by szwedm** [comment]
Status update:
> 2. Create a script that will update existing records in DB where Kyma version field is empty - in progress
Update query was created to fill the kyma_version field in Runtime states accordingly to version provided in runtime_version field in Operations. Every Runtime state is associated with Operation which ran on that runtime.

1. Code the logic in KEB for storing Kyma version in KymaVersion field when dealing with ops related to 2.x. - done
2. Create a script that will update existing records in DB where Kyma version field is empty - done
3. Optimize the following query to fetch the latest runtime state with Kyma version - in progress

**Comment by szwedm** [comment]
> 3. Optimize the following [query](https://github.com/kyma-project/control-plane/pull/825/files#r759410773) to fetch the latest runtime state with Kyma version - in progress

PR with requested optimization: https://github.com/kyma-project/control-plane/pull/1320

1. Code the logic in KEB for storing Kyma version in KymaVersion field when dealing with ops related to 2.x. - done
2. Create a script that will update existing records in DB where Kyma version field is empty - done
3. Optimize the following query to fetch the latest runtime state with Kyma version - done

**Comment by wozniakjan** [comment]
well done @szwedm, thanks!
