### ISSUE TITLE
Implement UpgradeKymaOperation with steps

### ISSUE THREAD

**Issue by polskikiel** [kyma-project/control-plane#136]
#### `process/upgrade/kyma` package
The package's main purpose is to implement the `UpgradeKymaManager` which encapsulates the logic to perform an idempotent Kyma upgrade operation on a given SKR. The operation shall be persisted in a `UpgradeKymaOperation` object stored in the DB.

`The Execute(operationID string) (time.Duration, error)` method of UpgradeKymaManager shall:

1. Get the operation from storage, bail out if completed or in case of error
2. If an operation is in progress, the manager picked up operation which was in progress after a restart. Poll/wait for the provisioner operation to finish, see step 6.
3. Assemble Kyma desired state 
- config.KymaVersion
- additionalComponents list from YAML config, merged with any optional components specified as a provisioning parameter  
- before (can vary based on plan: default, lite, trial)
  - Merged overrides from (can vary based on plan: default, lite, trial)
  - static ConfigMaps and Secrets
  - (Dynamically generated as part of provisioning operation (is it needed to be merged for comparison ???))
4. Get the current state of the runtime using runtimeStatus provisioner query.
5. Check if there is a difference between the desired state versus the corresponding attributes of the actual state (returned by the above query)
- Trigger upgradeRuntime mutation. The KymaConfig parameter should only contain those ConfigEntry elements which have changed.
6. Poll for the operation using runtimeOperationStatus until it finishes (either failed or succeeded state).
7. Return with error in case of failure, else return with nil

**AC:**
- within the `process/upgrade/kyma` package implement:
  - `UpgradeKymaOperation` steps
  - `UpgradeKymaManager` which implements described above `The Execute(operationID string) (time.Duration, error)` method and based on `UpgradeKymaOperation` in storage.
(see provisioning and deprovisioning implementations as examples)

*`UpgradeKyma` naming is important because KEB will support 2 types of upgrades in the future - Kyma upgrade and cluster upgrade, for now, we will implement only the Kyma upgrades.

epic #118

**Comment by ksputo** [comment]
Info form @ebensom :
```
One important thing about the provisioner upgradeRuntime API usage: Even though if you calcluate the desired kyva version / config / components list , and see there is a difference between desired and the current returned by runtimeStatus query, you need to provide the full components list and configurations lists for each component and global as provisioner only stores the JSON Blob set by the last upgradeRuntime call
```
