### ISSUE TITLE
KEB: Provide a user-facing message that can be used to tell the user details about the status of the operation.

### ISSUE THREAD

**Issue by PK85** [kyma-project/control-plane#1362]
**Description**

We need to inform users how provisioning, de-provisioning or update operations are going. The BTP cockpit will display up to date last operation description from KEB.

**Reasons**

Users do not know what is a progress of the installation.

**Currently**
Payload we return when ERS calls `GET /v2/service_instances/:instance_id/last_operation`

```
{
	"description": "Operation with instance_id 268BE0C0-8A65-461D-9FBE-307D1F6A5DEF not exist"
}
```
**AC**

- calculate progress of the installation, deinstallation, upgrade by analysing reconciler inventory response in a format of x/y. X is number of ready components and  Y is a number of all components. 
- produce payload for provisioning like: 
```
{
  "state": "in progress",
  "description": "Creating service (1/14 components)."
}
```
- produce payload for de-provisioning like: 
```
{
  "state": "in progress",
  "description": "Deleting service (1/14 components)."
}
```
- produce payload for update like: 
```
{
  "state": "in progress",
  "description": "Updating service (1/14 components)."
}
```

**Reconciler inventory example:**
```
		{
			"component": "logging",
			"correlationID": "3377c23f-b6dd-4f54-a78d-8145f4d6f444--7e6d7c44-a634-4918-a407-349eb46270bd",
			"created": "2022-02-16T04:09:40.074684Z",
			"priority": 4,
			"reason": "",
			"schedulingID": "3377c23f-b6dd-4f54-a78d-8145f4d6f444--4876414b-1486-4ad9-b643-f950d71cb4ff",
			"state": "done",
			"updated": "2022-02-16T04:13:58.986686Z"
		},
```

**Comment by tobiscr** [comment]
Would be great to return also an indicator for the issue that happened on our side (e.g. provide the KEB oepration-ID etc. so that customers can use it when raising issue tickets on Kyma side).
