### ISSUE TITLE
KCP CLI command to purge reconciliation records for removed runtimes

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/control-plane#1365]
**Description**

Provide possibility to purge reconciliation (i.e with `with kcp reconciliations purge`) that will remove the lingering reconciliation if the shoot was forcefully removed

- [x] enhance reconciliation repository to remove reconciliations of a cluster
- [x] add HTTP endpoint to mothership to delete reconciliations of a cluster
- [x] add new command to the KCP CLI which allows purging reconciliations of a clusters

**Reasons**

As an operator I want to purge records that are not relevant anymore.

**Comment by Cortey** [comment]
@tobiscr Should we permanently remove the record from the database or mark the reconciliation as "deleted" and filter it out in all selects?

**Comment by tobiscr** [comment]
Hi @Cortey - just mark it as deleted. This should - in the existing selects - already be enough to ignore it.

The cleaner module in the component reconciler will drop it then after X days automatically.

**Comment by Cortey** [comment]
@lumi017 If you re dropping the shoot the reconciler logic will keep it running as long as the cluster is in the inventory.  We have a cleaner that will drop anything older than 4 days. Is this feature really needed, if you re dropping the shoot you should make sure the cluster is deleted from the inventory and everything else will happen automatically.

**Comment by lumi017** [comment]
We will be getting alerted for failed reconciliations on prod, therefore we can't wait 4 days for the cleanup there. We need a way to manually trigger it for a shoot with  something like `kcp reconciliations purge`
