### ISSUE TITLE
KMC excessively reports "secrets XXXX.kubeconfig not found" errors

### ISSUE THREAD

**Issue by pxsalehi** [kyma-project/control-plane#1640]
**Description**

On KCP Dev, KMC frequently fires alerts regarding errors for requests from KMC to Gardener:
```
Rate of increase in errors for the requests from KMC to Gardener.
```

After analysing the errors in the KMC logs and prometheus metrics, all of the errors seem to be due to either not being able to find the secret (which contains the Kubeconfig data on the seed cluster to access the shoot cluster), or not being able to find the Shoot CR. The former case happens more often and generates logs and metrics, e.g:
```
{"level":"ERROR","timestamp":"...","caller":"process/process.go:321","message":"generate new metric for subAccount","component":"kmc","result":"fail","error":"secrets \"xxx.kubeconfig\" not found","SubAccountID":"xxx"}
```

However, in both cases, this is a not-found error, rather than error in reaching Gardener from KMC. Therefore, we should distinguish between 404 errors such as the above, and do not consider that for [the existing alert](https://github.com/kyma-project/control-plane/blob/8c7a89d3660b9a56f75c3e2007c5b9063ff9b921/resources/kcp/charts/kyma-metrics-collector/prometheus/alerts.yaml#L59) which has a critical severity. IMO, at most a warning should be issued for such cases.

As for why there are such errors (secret not found) happening, I could not find any specific reason. Unfortunately, the log files of KMC and Reconciler/KEB cannot be correlated for the past 90 days. To improve this, we should include the `RuntimeID` in the logs of KMC in addition to `SubAccountID`.

**Comment by marcobebway** [comment]
The secret not found error occurs because one of the following reasons:
- The shoot cluster was de-provisioned by KEB.
- The shoot cluster was deleted manually not by KEB.
In both cases the secret does not exist, hence there is a [PR](https://github.com/kyma-project/control-plane/pull/1864) to not report this as an error metric.
