### ISSUE TITLE
Make BTP Services support optional

### ISSUE THREAD

**Issue by PK85** [kyma-project/control-plane#1755]
**Description**
This ticket is about doing cleanup in the service management for Kyma instances. Only BTP operator way of enabling SAP services must be supported, and must be optional. That means btp-operator will be installed only when KEB receives credentials during provisioning.

**AC**
1) - [x] stop supporting sm_platform credentials. If they will be sent to KEB do not use them, and do not fail operation. Proceed with installation like with btp-operator credentials, I mean do not install service-catalog, helm-broker etc. We need to remove defaulting sm_platform credentials feature and do proper cleanups in BTP accounts too.
2) - [x]  btp-operator credentials must be optional. 
  2.1) - [ ] When provided install btp-operator, if not just kyma without service-catalog, helm-broker etc
  2.2) - [ ] In case of update operation when btp-operator credentials are not provided (for example update node min/max) keep btp-operator on the component list for reconciler (I mean DO NOT DEINSTALL)
3) - [ ] update all existing documentation. Including docs about how to spin Kyma cluster via KEB.

**Info**
- Example: we have suspended trial cluster with Service Catalog, after unsuspension sm_platform credentials will be provided and we will install Kyma as described in AC 1)
- btw if any Kyma insstance has persissted sm_plafform creds in KEB DB, we should stop to use it. For example in case of trial unsuspension. If update active=true comes, do not use them from KEB DB, just erase them, at leasts do not use

**Comment by piotrmiskiewicz** [comment]
Update SKR with BTP operator:
1. create with a payload ```{
				"service_id": "47c9dcbf-ff30-448e-ab36-d3bad66ba281",
				"plan_id": "361c511f-f939-4621-b228-d0fb79a1fe15",
		
				"context": {
					"globalaccount_id": "e449f875-b5b2-4485-b7c0-98725c0571bf",
						"subaccount_id": "pmiskiew",
						"user_id": "piotr.miskiewicz@sap.com",
					"sm_operator_credentials": {
					    "clientid": "testClientID",
					    "clientsecret": "testClientSecret",
					    "sm_url": "https://service-manager.kyma.com",
					    "url": "https://test.auth.com",
					    "xsappname": "testXsappname2"
				  }
					
				},
				"parameters": {
					"name": "pm-aws-operator"
					
				}
			}	```

then update with payload:
```
{
				"service_id": "47c9dcbf-ff30-448e-ab36-d3bad66ba281",
				"plan_id": "361c511f-f939-4621-b228-d0fb79a1fe15",
		
				"context": {
					"globalaccount_id": "e449f875-b5b2-4485-b7c0-98725c0571bf",
						"subaccount_id": "pmiskiew",
						"user_id": "piotr.miskiewicz@sap.com",
					"sm_operator_credentials": {
					    "clientid": "testClientID",
					    "clientsecret": "testClientSecret",
					    "sm_url": "https://service-manager.kyma.com",
					    "url": "https://test.auth.com",
					    "xsappname": "testXsappname2"
				  }
					
				},
				"parameters": {
					"name": "pm-aws-operator",
"autoScalerMax":7
					
				}
			}	
```

**Comment by pbochynski** [comment]
Q3 is over. Please update the timeline.
