### ISSUE TITLE
Split KEB into two separate pods: controller and REST API

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/control-plane#179]
**Description**

KEB processing logic requires running in a one instance which may cause a downtime when a new version is being rolled out. The REST API must be available without downtime, but the controller (queues processing) could be stopped for a short time.

AC:
- KEB REST API must be available without any downtime (replicas=2 on stage/prod)
- separate Pod for KEB controller
- documentation update

**Reasons**

The controller must work as one instance, the REST API must working without any downtime.

**Attachments**

**Comment by pbochynski** [comment]
I think we need bigger refactoring for control plane area. Let's plan it separately.
