### ISSUE TITLE
Remove ORY oathkeeper from KCP

### ISSUE THREAD

**Issue by strekm** [kyma-project/control-plane#1804]
**Description**

Remove ORY oathkeeper component from control plane. Charts should be cleaned along with any configuration. ORY oathkeeper component (helm release) should be removed from dev, stage and prod cluster (managed kyma) also with configuration (overrides). Corresponding resources (CRDs, CRs) should be removed from charts and from clusters. Documentation update if needed.

ACs:
- [x] ORY oathkeeper removed from charts with configuration
- [x] ORY oathkeeper removed from MPS cluster (dev, stage, prod)
- [x] ORY oathkeeper overrides removed from MPS (dev, stage, prod)
- [x] ORY oathkeeper CRDs & CRs removed
- [x] documentation updated if needed

**Reasons**

Dropping dependency to ORY oathkeeper

**Attachments**

Depends on: https://github.com/kyma-project/control-plane/issues/1732
Part of: https://github.com/kyma-project/control-plane/issues/1540

**Comment by barchw** [comment]
PR for this issue: https://github.com/kyma-project/control-plane/pull/1892

**Comment by barchw** [comment]
Waiting for https://github.tools.sap/kyma/management-plane-config/pull/1884
