### ISSUE TITLE
Fix UpgradeShoot Provisioner test

### ISSUE THREAD

**Issue by Szymongib** [kyma-project/control-plane#188]
**Description**

After some changes in Gardener and Provisioner, the `UpgradeShoot` test is no longer working, as the upgrade fails with the operation timeout.

As part of troubleshooting, consider:
- Checking any errors returned by Gardener when performing an upgrade
- Verifying the Shoot resource is correctly upgraded
- Manual Shoot upgrade with parameters used by the test

**Todo:**
- Find a reason why the test is failing (is it misconfiguration or random)
- Try to fix the test, so that the `UpgradeShoot` finish with success

**Comment by Disper** [comment]
New idea:
- Make component lists as short as possible to reduce time needed for installation (Istio, Compass Runtime Agent(needed for provisioning), Application Connector (probably?)
- Something to consider that we were not sure about during the refinement meeting: separate pipeline for monitoring of the running status of provisioning.

**Comment by janmedrek** [comment]
Merging with a similar issue: https://github.com/kyma-project/control-plane/issues/84
