### ISSUE TITLE
KEB - support bulk Kyma upgrade

### ISSUE THREAD

**Issue by PK85** [kyma-project/control-plane#189]
**Description**
Next iteration for Kyma upgrades by KEB. Besides main bulk upgrade feature, KEB will get some additional small improvements, see AC.

**Reason**
Operators will be able to upgrade all Runtimes in easy way.

**AC**

- findings from MVP implementation
  - fix current database design how we store runtimeOperations. Right now we are forced to fetch all operations for given orchestration. When we will want to implement paging or filtering that will be big issue.
  - renew processing orchestration when KEB restarts
  - persist every change on operation immediately (not at the end, when we can lose data when KEB restarts)
  - process only one Orchestration at time
  - refactor `RuntimeOperation` and `UpgradeKymaOperation` to somehow create only one object

- implement bulk upgrade, include#target "all" 
- add swagger console into root KEB URL
- improve swagger details. Describe all values (fixed ones) of statuses etc.
- implement /orchestration/id/operation/id which will have additional information, like overrides etc
  - encrypt all data persisted by KEB ( including overrides (input for upgrade)).
  - ~~maybe whole KEB DB data should be encrypted~~
  - encrypt existing data
- parallel strategy implementation
- support time windows for upgrade (Check if we for sure should use gardener maintenance window)
- GET /runtimes - extend upgrading field with upgradeHistory list (every item has own createdAt)
  - put infomration about orchestration id (to find deatils about given upgrade)
- adjust documentation with all new features (new scopes like runtimes:read, /runtimes endpoint too)
- /orchestration endpoint (a list of orchestrations) does not return runtime operations which is available in /orchestration/id endpoint
- test bulk upgrade with few real clusters

**Linki**
- previous MPV Story - https://github.com/kyma-project/control-plane/issues/118

**Next iteration**
- filtering options for example: succeded etc
- ability to cancel pending orchestration 
  - consider cancel in progress orchestrations (with strategy still check all in progress operations)
- update orchestration (probably we should never support that)
- check how often gardener has maintanence windows (is that up to customer? I guess not)

**Comment by ebensom** [comment]
Hi @PK85 @piotrmiskiewicz ,
Swagger UI might not be needed as we are about to start developing an SKR CLI for operators, which will be our primary tool for interacting with the exposed API

**Comment by piotrmiskiewicz** [comment]
Proposed example of an entry in /runtimes endpoint:

```json
{
      "instanceID": "7690d256-7278-433a-a0e1-69eba2291ea9",
      "runtimeID": "95e75083-9178-4600-8dc9-05e8c16ecb2c",
      "globalAccountID": "3e64ebae-38b5-46a0-b1ed-9ccee153a0ae",
      "subAccountID": "39ba9a66-2c1a-4fe4-a28e-6e5db434084e",
      "subAccountRegion": "cf-eu10",
      "shootName": "c-3b71f0c",
      "serviceClassID": "47c9dcbf-ff30-448e-ab36-d3bad66ba281",
      "serviceClassName": "kymaruntime",
      "servicePlanID": "4deee563-e5ec-4731-b9b1-53b42d855f0c",
      "servicePlanName": "azure",
      "status": {
        "createdAt": "2020-09-10T15:30:46.681994Z",
        "modifiedAt": "2020-09-10T16:15:47.541435Z",
        "provisioning": {
          "state": "succeeded",
          "description": "Operation created : Operation succeeded"
        },
       "deprovisioning": {
          "state": "succeeded",
          "description": "Operation created : Operation succeeded"
        },
        "upgradingKyma": [
           {
              "state": "succeeded",
              "description": "Operation created : dry run succeeded"
               "createdAt":"2020-09-10T16:15:37.541435Z"
               "orchestrationID: "4faa67aa-5d65-4097-b0e4-084e2b94be0e"
           },
          {
              "state": "succeeded",
              "description": "Operation created : dry run succeeded",
              "createdAt":"2020-09-10T16:15:47.541435Z",
              "orchestrationID: "3bbcd349-6c8b-440e-9d4c-d86d1d52d894"
           }
        ]
      }
    }
```

**Comment by PK85** [comment]
Yes, filter out dryruns

**Comment by PK85** [comment]
Idea:

```
"upgradingKyma": {
           
           "data": [{
              "state": "succeeded",
              "description": "Operation created : dry run succeeded",
               "createdAt":"2020-09-10T16:15:37.541435Z",
               "orchestrationID": "4faa67aa-5d65-4097-b0e4-084e2b94be0e",
               "operationID": "5ac1846a-22fa-4d89-9ab1-bb4a0ed08510"
           },
          {
              "state": "succeeded",
              "description": "Operation created : dry run succeeded",
              "createdAt":"2020-09-10T16:15:47.541435Z",
              "orchestrationID": "3bbcd349-6c8b-440e-9d4c-d86d1d52d894",
              "operationID": "e80507bb-07b7-45bc-9005-939f999d09d0"
           }
],
 "count": 0,
  "totalCount": 0
        }
```
