### ISSUE TITLE
Change the administrator binding label to something more appropriate

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/control-plane#1912]
PR for review https://github.com/kyma-project/control-plane/pull/2866

Follow Up Issue: https://github.com/kyma-project/control-plane/issues/2858 

**Description**

We would need to use something better suited than the `type=admin` label on the administrator Role Binding that we use right now.

We could potentially use:
- `reconciler.kyma-project.io/managed-by=reconciler` that is implemented right now and blocks any editing in Busola
- `provisioner.kyma-project.io/managed-by=provisioner` to mimic the approach we have in reconciler

With the Cluster Operator in mind, the first option makes sense and it could be considered - at some point Provisioner will be migrated to the reconciler scheme.

Also, we could potentially think about `reconciler.kyma-project.io/managed-by=provisioner` if Busola is somehow configured to only block resources based on the label key.

**Reasons**

We want to have clear labels that indicate which resources are managed by the Control Plane.

**Acceptance Criteria**

- Label changed to something that indicates the Binding is managed by the Provisioner.
- Provisioner should remove bindings with both `type=admin` and the new `reconciler.kyma-project.io/managed-by=reconciler` labels during the upgrade (and then apply the desired ones), this is to avoid name conflicts with existing bindings that use the old label. Later on, the Cluster Operator should use only the new label.

**Comment by janmedrek** [comment]
Deletion of labelled bindings: https://github.com/kyma-project/control-plane/blob/fc5da85e9872f49a5e73910733503ee549112029/components/provisioner/internal/operations/stages/provisioning/create_operators_bindings.go#L139

and the creation: https://github.com/kyma-project/control-plane/blob/fc5da85e9872f49a5e73910733503ee549112029/components/provisioner/internal/operations/stages/provisioning/create_operators_bindings.go#L131

**Comment by koala7659** [comment]
More details for developers: 

During Kyma cluster creation process provisioner creates some Kubernetes `clusterroles` and `clusterrolebindings` on newly provisioner Gardener cluster (gardener shoot). Those objects are required later on for correct setup of the cluster. As described in the original issue description labeling of one of the bindings should be changed. 

**More source code context:** 

The step of creating those  `clusterroles` and `clusterrolebindings` is part of the provisioning queue executed immediately after fresh Kubernetes cluster becomes active as the third operation (should be read from the bottom).

The provisioning queues are built in the file  

`components/provisioner/internal/operations/queue/queues_constructor.go`
For Kyma 1.x

```
waitForAgentToConnectStep := provisioning.NewWaitForAgentToConnectStep(ccClientConstructor, configurator, model.FinishedStage, timeouts.AgentConnection, directorClient)
configureAgentStep := provisioning.NewConnectAgentStep(configurator, waitForAgentToConnectStep.Name(), timeouts.AgentConfiguration)
waitForInstallStep := provisioning.NewWaitForInstallationStep(installationClient, configureAgentStep.Name(), timeouts.Installation, factory.NewWriteSession())
installStep := provisioning.NewInstallKymaStep(installationClient, waitForInstallStep.Name(), timeouts.InstallationTriggering)
createBindingsForOperatorsStep := provisioning.NewCreateBindingsForOperatorsStep(k8sClientProvider, operatorRoleBindingConfig, installStep.Name(), timeouts.BindingsCreation)
waitForClusterCreationStep := provisioning.NewWaitForClusterCreationStep(shootClient, factory.NewReadWriteSession(), gardener.NewKubeconfigProvider(secretsClient), createBindingsForOperatorsStep.Name(), timeouts.ClusterCreation)
waitForClusterDomainStep := provisioning.NewWaitForClusterDomainStep(shootClient, directorClient, waitForClusterCreationStep.Name(), timeouts.ClusterDomains)
```

For Kyma 2.x
```
configureAgentStep := provisioning.NewConnectAgentStep(configurator, model.FinishedStage, timeouts.AgentConfiguration)
createBindingsForOperatorsStep := provisioning.NewCreateBindingsForOperatorsStep(k8sClientProvider, operatorRoleBindingConfig, configureAgentStep.Name(), timeouts.BindingsCreation)
waitForClusterCreationStep := provisioning.NewWaitForClusterCreationStep(shootClient, factory.NewReadWriteSession(), gardener.NewKubeconfigProvider(secretsClient), createBindingsForOperatorsStep.Name(), timeouts.ClusterCreation)
waitForClusterDomainStep := provisioning.NewWaitForClusterDomainStep(shootClient, directorClient, waitForClusterCreationStep.Name(), timeouts.ClusterDomains)
```
The  code executed to create cluster roles and custerrolebindings is executed in the Run method of the step

` func (s *CreateBindingsForOperatorsStep) Run(cluster model.Cluster, _ model.Operation, log logrus.FieldLogger)`


To verify if this code works and its result - we can take any provisioned Kyma runtime and after logging with  kubecoinfig execute:

`k get clusterroles --show-labels`

```
l2-operator    2022-10-12T09:23:30Z   app=kyma
l2-operator-rules  2022-10-12T09:23:30Z   app=kyma,rbac.authorization.k8s.io/aggregate-to-l2-operator=true
```

To find clusterrolebing to fix: 
`k get clusterrolebindings --show-labels | grep type=admin`

`administrator0                  ClusterRole/cluster-admin             6h20m   app=kyma,type=admin`

Which is effect of the following code:

```
clusterRoleBindings = append(clusterRoleBindings,
   buildClusterRoleBinding(
      fmt.Sprintf("%s%d", administratorOperatorClusterRoleBindingName, i),
      administrator,
      ownerClusterRoleBindingRoleRefName,
      userKindSubject,
      map[string]string{"app": "kyma", "type": "admin"}))
```

**Comment by janmedrek** [comment]
Hey, @kyma-project/framefrog, I believe this issue should not be closed, this still would bring value for the Kyma users.

Do you have other opinions on that? Is there a reason to skip the implementation?

**Comment by VOID404** [comment]
Currently new label is added, but old (`type=admin`) is still present.  We currently remove by `type=admin`. The only part missing is changing the remove filter, and not adding `type=admin`

**Comment by lautoma** [comment]
@VOID404 any plans to continue/finalize the implementation from this issue?

**Comment by akgalwas** [comment]
@lautoma We will work on it in the next sprint starting 12th of June.

**Comment by lautoma** [comment]
@akgalwas I see that you moved this issue to Done, however it's still open. When (in which release) will this implementation be available?

**Comment by Disper** [comment]
This issue was fixed by https://github.com/kyma-project/control-plane/pull/2866.

**Comment by koala7659** [comment]
@lautoma The update was delivered to Kyma Control Plane not for any particular Kyma release. It was deployed to production about 3 weeks ago so it can be correlated with Kyma 2.15
