### ISSUE TITLE
KEB dependabot blocked by KCP CLI check

### ISSUE THREAD

**Issue by wozniakjan** [kyma-project/control-plane#1929]
**Description:**
- every PR to KEB newly needs to pass KCP CLI check which runs `go mod tidy` - https://github.com/kyma-project/test-infra/pull/5776
- KCP CLI vendors KEB
- KEB dependabot bumps various go modules for KEB
- transitively, KCP CLI pulls dependabot changes if the go modules resolver deems so necessary
- ^^ results in every KEB dependabot PR regarding go modules automatically blocked by PR checks

**Examples:**
- [ ] https://github.com/kyma-project/control-plane/pull/1896
- [ ] https://github.com/kyma-project/control-plane/pull/1926
- [ ] https://github.com/kyma-project/control-plane/pull/1895

**Comment by wozniakjan** [comment]
I think there are potentially few paths forward
1. disable the KCP CLI mod check on KEB PRs - arguably it's not the correct place to run that check and KCP CLI should maintain its own go mods on PRs to KCP CLI. But there is also the fact these two programs live in the same repository which could mean we do instead:
2. on every dependabot KEB PR, trigger a github action amending a new commit with `go mod tidy` executed under the KCP CLI directory.

**Comment by wozniakjan** [comment]
cc @pPrecel @Halamix2

**Comment by kwiatekus** [comment]
@wozniakjan We are a little bit short with developers this week, but we will look into this in the following one.

**Comment by wozniakjan** [comment]
thanks @kwiatekus, it's not urgent. It's just the dependabot has been very useful in keeping up to date with the KEB dependencies and also greatly lowering the number of security scanner vulnerabilities reported so it would be nice to keep it working in an automated fashion rather than having some manual steps in the process.

**Comment by wozniakjan** [comment]
temporary remediation in https://github.com/kyma-project/control-plane/pull/1934
