### ISSUE TITLE
KEB: ClusterState

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/control-plane#197]
**Description**

Every change in the SKR should make a immutable record in the DB which descries such SKR state with the following information:
 - kyma config
 - cluster config
 - type (runtime, shoot)
 - timestamp
 - operationID, runtimeID
 - kymaVersion, k8sVersion

It will be created on:

- success provisioner call

**Comment by pbochynski** [comment]
@piotrmiskiewicz Please add labels!
