### ISSUE TITLE
Deprecate usage of legacy github.com/pkg/errors

### ISSUE THREAD

**Issue by wozniakjan** [kyma-project/control-plane#2073]
KEB still uses legacy https://github.com/pkg/errors, which is replaced by core go error wrapping since go 1.13 https://go.dev/blog/go1.13-errors.

Additional background in https://github.com/kyma-project/control-plane/pull/2072

**Comment by tillknuesting** [comment]
https://github.com/pkg/errors is archived hence it would make sense to migrate to the standard library to wrap errors.

**Comment by tillknuesting** [comment]
Are both error wrapping methods compatible?
No

What happens if unwrap is called on a single base error that does not have another wrapped error?

_pkg/errors_ return a base error even when a unwrap is called. 
`errors` will return nil if unwrap is called on a base error that does not wrap another error

Possible to check for error recursively and multiple wrapped errors?

Cause function checks recursively all nested errors and returns the last one while the standard Unwrap function returns the first one without recursion.

Call-stack print?

Standard library does not track call-stack and prints much less information.


--------------------------------

Here is an example using both

```
package main

import "github.com/pkg/errors"

// Wrapped returns wrapped error
func Wrapped() error {
	internal := errors.New("internal error")
	return errors.Wrap(internal, "wrapper")
}

// ErrorsStack wraps error two times
func ErrorsStack() error {
	err := Wrapped()
	return errors.Wrap(err, "another wrapper")
}
```


```
package main

import (
	"errors"
	"fmt"
)

// Wrapped returns wrapped error
func Wrapped() error {
	internal := errors.New("internal error")
	return fmt.Errorf("wrapper: %w", internal)
}

// ErrorsStack wraps error two times
func ErrorsStack() error {
	err := Wrapped()
	return fmt.Errorf("another wrapper: %w", err)
}
```

**Comment by tillknuesting** [comment]
Added example refactor PR how to wrap errors https://github.com/kyma-project/control-plane/pull/2098/files

**Comment by wozniakjan** [comment]
@tillknuesting I think the only place that really uses the error wrapping is metrics error categorization introduced in https://github.com/kyma-project/control-plane/pull/1369. 

Especially this file:
https://github.com/kyma-project/control-plane/blob/c23eaa33264b2f1d962ee64166294c59200e42d2/components/kyma-environment-broker/internal/error/errors.go#L90

@vvxxvvxx can provide more information regarding how it is then used in alerting, we would like it to continue working even after the change introduced in https://github.com/kyma-project/control-plane/pull/2098

**Comment by tillknuesting** [comment]
`Regarding the `func ReasonForError(err error) LastError`` the main challenge is to replace the cause method of errors package with the same functionality.

**Comment by tillknuesting** [comment]
Also, checkK8SError needs to be refactored

**Comment by vvxxvvxx** [comment]
From this post, we could see at the current moment, maybe replacing https://github.com/pkg/errors is not a good choice. https://itnext.io/golang-error-handling-best-practice-a36f47b0b94c

![image](https://user-images.githubusercontent.com/48271609/194803144-1f8f0750-ff52-49ad-ac86-eb5eaec63ac5.png)

![image](https://user-images.githubusercontent.com/48271609/194803183-7fc27a3f-cd9a-4e47-90f6-11d7fd876491.png)

![image](https://user-images.githubusercontent.com/48271609/194803219-b856e534-c5a7-42d5-a435-e030c0318cac.png)

![image](https://user-images.githubusercontent.com/48271609/194803247-f08a4372-90db-476e-901a-8c8a7eafbe2a.png)

even though https://github.com/pkg/errors is public archived, but the method/logic is good enough to use comparing to the current errors in core standard go. https://github.com/pkg/errors has no security risk and can provide better errors handling. Why can't we continue to use it until go2 is released? errors handling in core standard go is now under consideration and not mature enough, maybe it will be settled in go2. 
would be better to wait and see, and suggest we keep using https://github.com/pkg/errors as we now are still using go1.* .

**Comment by tillknuesting** [comment]
PO decided to go ahead with the refactor to errors from the standard library.
