### ISSUE TITLE
KEB: Provide credentials into Runtime for BTP Manager module

### ISSUE THREAD

**Issue by PK85** [kyma-project/control-plane#2116]
**Description**

This requirement applies for Kyma installations managed by lifecycle-manager and BTPManager is already in use. For old installations secret is provided to reconciler.

![2022-10-06 BTP-Manager credentials](https://user-images.githubusercontent.com/9609118/194261437-e35456ab-7617-4607-be5a-8509ca7bb58d.png)

**Reasons**

Lifecycle-manager do not support passing any configuration into Runtimes.

**AC**

- [x] 1) Double check what we pass to reconciler in current implementation, in a new way we should pass at least:
  - [x] a) btp-operator credentials into runtime that could be consumed by btp-operator controller
  - [x] b) clusterID as configMap for btp-operator controller
- [ ] 2) Provide tests if BTP-operator works as expected with that new way of passing configurations
- [x] 3) Provide KEB documentation

**Comment by jaroslaw-pieszka** [comment]
Draft PR: https://github.com/kyma-project/control-plane/pull/2156

**Comment by jaroslaw-pieszka** [comment]
### **Meeting minutes** 
Date: 18.10.2022 2pm-3pm
Present: @PK85 @piotrmiskiewicz @szwedm @ukff 

### **Decisions made:**

1. Dedicated secret as the contract between KEB and BTP Manager. The secret conveys all data that need to be passed from KEB to BTP Manager. Secret is used solely by BTP Manager, not by the BTP Operator. Secret contains BTP Operator credentials and ClusterID.

> Reasons
> 
> - simplification of contract
> - separation of duties: KEB does not have to be aware neither of relationship between BTP Manager and BTP Operator nor of theirs lifecycles, KEB would not be responsible for restarting pod in case of update of the secret
> - chart for BTP Operator requires ClusterID upfront 


2. Secret is created always when BTP Operator credentials are present regardless there is BTP Manager to use it.

> Reason
> - backward compatibility and simplification of logic

3. Upgrade operation is to be enhanced and facilitate creation of the secret for all clusters.

> Reason 
> - to ensure the secret is present on all clusters when we switch to use Life Cycle Manager instead of Reconciler.

**Comment by jaroslaw-pieszka** [comment]
### Contract between KEB and BTP Manager as for the secret

```
	TypeMeta:   v1.TypeMeta{Kind: "Secret"},
	ObjectMeta: v1.ObjectMeta{Name:"sap-btp-manager". Namespace: "kyma-system"},
	StringData: map[string]string{
		"clientid":       credentials.ClientID,
		"clientsecret":   credentials.ClientSecret,
		"sm_url":         credentials.ServiceManagerURL,
		"tokenurl":       credentials.URL,
		"tokenurlsuffix": credentials.XSAppName,
		"cluster_id":     clusterID},
	Type: coreV1.SecretTypeOpaque,
```
**Labels**:
```
	"kyma-project.io/managed-by": "kcp-kyma-environment-broker",
	"kyma-project.io/provided-by": "kcp-kyma-environment-broker",
```
**Annotation**:
TBD

**Comment by PK85** [comment]
@jaroslaw-pieszka @szwedm which label will be the one that BTP-Manager requires?

**Comment by jaroslaw-pieszka** [comment]
> @jaroslaw-pieszka @szwedm which label will be the one that BTP-Manager requires?
> 
> Btw
> 
> ```
> 	"kyma-project.io/managed-by": "kcp-kyma-environment-broker",
> 	"kyma-project.io/provided-by": "kcp-kyma-environment-broker",
> ```
> 
> They mean the same right? Then maybe just use only kyma-project.io/managed-by.

Comment updated. The answer to your question is below:
"kyma-project.io/required-by": "btp-manager"

**Comment by jaroslaw-pieszka** [comment]
Contract updated as a result of mutual agreement between @szwedm and @jaroslaw-pieszka.

**Comment by jaroslaw-pieszka** [comment]
PR with additional step for review: https://github.com/kyma-project/control-plane/pull/2156
E2E test implementation in separate PR
