### ISSUE TITLE
Reuse common clients' logic in control-plane

### ISSUE THREAD

**Issue by ksputo** [kyma-project/control-plane#216]
**Description**
In control-plane we use many clients for internal services, mostly in case of testing those dependencies. Having those in `internal` directory prevents from importing the clients in `tests` directory. This was part of investigation in [#1303](https://github.com/kyma-incubator/compass/issues/1303) and partially fixed from KEB perspective in #204 . Next step would be to unify rest of the duplicated clients code in control-plane repository and move the common package to the root directory, like we have in [kyma-project/kyma](https://github.com/kyma-project/kyma/tree/master/common):

```
.
├── common
│   ├── director
│   │   ├── client.go
│   ├── gardener
│   ├── hyperscaler
│   ├── provisioner
│   ├── other-code-shared-between-tests-and-components
├── components
│   ├── kubeconfig-service
│   ├── kyma-environment-broker
│   ├── metris
│   ├── provisioner
│   └── schema-migrator
├── docs
├── installation
├── resources
├── scripts
├── tests
└── tools
```

Therefore, all teams involved in `control-plane` development should be marked as CODEOWNERS of this directory.

At the moment, those are places where somehow duplicated code was found:
- [ ] [`control-plane/tests/provisioner-tests/test/testkit`](https://github.com/kyma-project/control-plane/tree/master/tests/provisioner-tests/test/testkit) - framefrog, @janmedrek 
- [ ] [`control-plane/tests/e2e/provisioning/internal/hyperscaler/azure`](https://github.com/kyma-project/control-plane/tree/master/tests/e2e/provisioning/internal/hyperscaler/azure) - skydivingtunas, @anishj0shi 

**Reasons**
Refactoring these parts will result in cleaner code without unnecessary code duplication.

**Attachments**

**Comment by pbochynski** [comment]
Is it done? @ksputo

**Comment by ksputo** [comment]
current state in KEB:
```
components/kyma-environment-broker/common
├── director
│   ├── automock
│   │   └── GraphQLClient.go
│   ├── client.go
│   ├── client_test.go
│   ├── config.go
│   └── query.go
├── gardener
│   ├── client.go
│   ├── config.go
│   └── shoot_name.go
├── hyperscaler
│   ├── account_pool.go
│   ├── account_pool_test.go
│   ├── account_provider.go
│   ├── account_provider_test.go
│   ├── automock
│   │   └── account_provider.go
│   ├── azure
│   │   ├── client.go
│   │   ├── config.go
│   │   ├── env.go
│   │   ├── env_test.go
│   │   ├── provider.go
│   │   ├── tags.go
│   │   └── testing
│   │       └── testing.go
│   ├── shared_pool.go
│   └── shared_pool_test.go
├── orchestration
│   ├── automock
│   │   ├── runtime_resolver.go
│   │   └── strategy.go
│   ├── client.go
│   ├── client_test.go
│   ├── dto.go
│   ├── ext.go
│   ├── resolver.go
│   ├── resolver_test.go
│   ├── runtime_lister_mock.go
│   └── strategies
│       ├── parallel.go
│       └── parallel_test.go
├── pagination
│   └── pagination.go
├── runtime
│   ├── client.go
│   ├── client_test.go
│   └── model.go
└── storage
    └── storage.go

13 directories, 38 files

```
