### ISSUE TITLE
KEB: implement grace period for deprovisioning instances

### ISSUE THREAD

**Issue by wozniakjan** [kyma-project/control-plane#2199]
Currently, KEB deletes instance entry as soon as deprovisioning operation is processed. This makes follow-up debugging and inspections more challenging. If KEB after the deprovisioning operation would just mark the instance as "deprovisioned" and then after some grace period finally deleted the entries in db, that could help with the visibility.

**Comment by PK85** [comment]
We discussed that ticket with @wozniakjan and @piotrmiskiewicz and decided to not implement that solution
