### ISSUE TITLE
KEB should reject instance update erroneous to multi AZ

### ISSUE THREAD

**Issue by ebensom** [kyma-project/control-plane#2371]
**Description**

There were several incidents recently where a multi AZ runtime was provisioned with `autoscalerMax` >= 3 value, and hence worker nodes were created in 3 AZs, all AZs hosting dynamically provisioned PVs. 
Later on the user updated the instance with `autoscalerMax = 2`, which caused one of the AZs to not have workers any more, and hence pods which claimed PV(s) in the AZ without any worker nodes were stuck in Pending state. 
 
KEB shall reject the instance update request if

- The instance is multi-AZ (could this be determined via stored parameters?)
- current `autoscalerMax >= 3`

**Comment by piotrmiskiewicz** [comment]
1. What about update with bigger autoscaler values?

**Comment by ebensom** [comment]
But once he updates `autoscalerMax >= 3` (so current parameter value is now >=3), he shouldn't be able to update it with `< 3` (e.g. `autoscalerMax = 2`) any more.

**Comment by ebensom** [comment]
Another 2 incidents happened in the last 7 days. 
@piotrmiskiewicz Do you foresee when this could be fixed in KEB?

**Comment by piotrmiskiewicz** [comment]
the final AC: 
 - the autoscalerMax param in the update request cannot be lower than number of availability zones

**Comment by PK85** [comment]
@piotrmiskiewicz 
Checklist:
- check how BTP Cokpit will behvae when we will return validation error. Does user see instance in error or ready.
