### ISSUE TITLE
KEB Overrides_From_Secrets_And_Config steps must fail if overrides not found

### ISSUE THREAD

**Issue by PK85** [kyma-project/control-plane#2378]
**Description**

Overrides_From_Secrets_And_Config are looking for static overrides for given version and plan. If not found, the process must fail instead of retry, which does not make sense.

**Expected result**

Steps fails in case of no overrides available

**Actual result**

Steps are retrying.

**Comment by MarekMichali** [comment]
Tests need to be added. PR:

**Comment by szwedm** [comment]
Fix has been provided. Closing.
