### ISSUE TITLE
Identify failed steps in KEB deprovisioning

### ISSUE THREAD

**Issue by wozniakjan** [kyma-project/control-plane#2392]
**Description**

At the moment, the deprovisioning processing queue is designed to log any failed steps but proceed further. And as long as Gardener succeeds in deleting the cluster which is the last step, mark the operation as successful. But this can leave cruft in various systems and residual resources behind without anyone paying attention as this information is buried by the volume of logs in the aggregated logging.

**Reasons**

There are situations where the residual resources left behind are filling up a quota that should normally be sufficient. As a result, some provisioning requests fail.

**AC**
- Implement this ticket: [KEB-core](https://github.com/kyma-project/control-plane/issues/2406)
- Implement this ticket: [KEB-cli]()
- Implement this ticket: [KEB-job]()
- When all the above points are implemented test given scenario:
  - Simulate step failure when deprovisioning SKR instance
  - Fix the problem of the failing step
  - Check if job did a proper cleanup

**Attachments**

**Comment by szwedm** [comment]
We need to store info of what failed and what is the reason of failure. We should be able to re-trigger the operation which has failed steps (EDP, AvS), so even when the cluster is gone we still should have the instance record in DB, but user shouldn't see the instance. There could be a job which runs deprovisioning again for such cases. This issue requires further analysis, SRE insights can help in finding the solution (how they gather data about instance deprovisioning for which operation hasn't successfully completed all the steps).

**Comment by piotrmiskiewicz** [comment]
1. Once the step cannot do the job and goes to next one, marks the operation  that such step needs a retry.
2. at the end, instance is not permanently removed, but marked as deleted (deleted_at)
3. the get_instance endpoint has a check, if deleted_at is set. If yes, returns 404 (or 410). Check if any instance contains this field in the DB.
4. kcp cli prints steps which needs retry
5. A job which triggers (creates new deprovisioning operation) for instances which need a retry.

**Comment by wozniakjan** [comment]
I have some availability so I will attempt to take a stab at KEB-core part.

**Comment by wozniakjan** [comment]
https://github.com/kyma-project/control-plane/issues/2407 has closed, unassigning myself

anything left for https://github.com/kyma-project/control-plane/issues/2408 @jaroslaw-pieszka and https://github.com/kyma-project/control-plane/issues/2406 @MarekMichali?

**Comment by MarekMichali** [comment]
#2406 is done

**Comment by ralikio** [comment]
- [ ] TODO: Documentation
