### ISSUE TITLE
KEB-core: Implement core logic in the KEB to be able to retry failed steps for deleted service instances

### ISSUE THREAD

**Issue by PK85** [kyma-project/control-plane#2406]
**Description**

This is part of [Identify failed steps in KEB deprovisioning](https://github.com/kyma-project/control-plane/issues/2392)
This ticket is about the main implementation in the KEB component.

**AC**

- Once the step cannot do the job and goes to the next one, marks the operation that such step needs a retry. All deprovisioning steps must be reviewed (13 steps). Consider some steps could fail deprovisioning instead of marking "needs to retry". Check if the page is still up to date: https://github.com/kyma-project/control-plane/blob/main/docs/kyma-environment-broker/03-03-runtime-operations.md
- at the end, the instance is not permanently removed, but marked as deleted (deleted_at)
- the get_instance endpoint has a check, if deleted_at is set. If yes, returns 404 (or 410). Check if any instance contains this field in the DB.

**Comment by MarekMichali** [comment]
Deprovisioning steps mentioned here https://github.com/kyma-project/control-plane/blob/main/docs/kyma-environment-broker/03-03-runtime-operations.md are up to date.

**Comment by MarekMichali** [comment]
First PR: #2412

**Comment by wozniakjan** [comment]
> at the end, the instance is not permanently removed, but marked as deleted (deleted_at)

I think it might be possible to keep the KEB behavior as is at the moment and it could be **\*not necessary\*** to keep the instance in the `Instances` table - https://github.com/kyma-project/control-plane/issues/2407#issuecomment-1398347464. KCP has `--only-deleted`, the failed steps are stored on the operation in `Operations` table and the GC job can find it there, but not sure how easy would it be to re-run operations if the entry from `Instances` table is gone.

**Comment by MarekMichali** [comment]
Second PR for marking operations that require retry: #2418
Covered steps:
- BTPOperator_Cleanup

**Comment by MarekMichali** [comment]
Third PR for marking operations that require retry: #2422 
Covered steps:
- Check_Cluster_Deregistration
- Deregister_Cluster
- EDP_Deregistration
- Release_Subscription

**Comment by MarekMichali** [comment]
PR for marking the instalce as deleted using deleted_at: #2429

**Comment by MarekMichali** [comment]
Think about metrics

**Comment by jaroslaw-pieszka** [comment]
Job retriggering deprovision - https://github.com/kyma-project/control-plane/pull/2449

**Comment by jaroslaw-pieszka** [comment]
Partially addressed in https://github.com/kyma-project/control-plane/pull/2491

We need to add check in case there is succeeded non-temporary (non suspension) operation with no incomplete steps.

**Comment by wozniakjan** [comment]
there appears to be another bug, the `delete_at` timestamp is not set after deprovisioning finished
```
broker=> select instance_id, created_at, deleted_at from instances where instance_id='test-jw665';
 instance_id |          created_at           |       deleted_at
-------------+-------------------------------+------------------------
 test-jw665  | 2023-02-20 15:10:12.971024+00 | 0001-01-01 00:00:00+00
(1 row)

broker=> select id, instance_id, created_at, state, type, data::json->>'excutedButNotCompleted' from operations where instance_id='test-jw665';
                  id                  | instance_id |          created_at           |   state   |    type     |             ?column?
--------------------------------------+-------------+-------------------------------+-----------+-------------+----------------------------------
 870b4b3d-f53a-4322-ad6a-a13d6c7d37ba | test-jw665  | 2023-02-20 15:10:12.966155+00 | succeeded | provision   |
 d373abf0-1a45-4890-939b-0883e8f274bf | test-jw665  | 2023-02-20 15:24:04.463983+00 | succeeded | deprovision | ["De-provision_AVS_Evaluations"]
(2 rows)
```

**Comment by wozniakjan** [comment]
fixing the oversight from https://github.com/kyma-project/control-plane/pull/2429 in https://github.com/kyma-project/control-plane/pull/2499, the DB query didn't set `deleted_at` field in the table.

**Comment by ralikio** [comment]
- [ ] TODO: Documentation

**Comment by MarekMichali** [comment]
- [] Find a way to set deletedAt to the default value when the deprovison retrigger job succedd
- [] Add test for scenario: deprovision finished with ExecutedButNotCompletedSteps -> deprovision retrigger finished without ExecutedButNotCompletedSteps -> instance deleted
- [] Add test for scenario deprovision finished with ExecutedButNotCompletedSteps  -> deprovision retrigger finished with ExecutedButNotCompletedSteps -> insatnce qualifies for another deprovision retrigger job

**Comment by MarekMichali** [comment]
Check scenario suspension -> deprovisioning

**Comment by jaroslaw-pieszka** [comment]
1. We identified another flaw in suspension -> deprovisioning scenario - for trials/freemium plans - scenario regarding AVS deregistration. 
2. Scenario suspension -> deprovisioning where we lost track of runtimeID - https://github.com/kyma-project/control-plane/pull/2513
3. Reconsider if there are any more scenarios that need tests or at least static analysis.

This is subjective opinion but using `deletedAt` for different purposes has a few disadvantages. 
A boolean flag marking logically deleted would more elegant solution.

**Comment by MarekMichali** [comment]
> kcp rt -i c728542b-8c47-4330-95ab-4ca3b04a70c2 --events --only-deleted

Instance successfully deprovisioned by the job with previous AVS problem

**Comment by MarekMichali** [comment]
Blocker discovered see #2545

**Comment by MarekMichali** [comment]
During testing discovered a bug in the deprovisioning test, see the fix #2555

**Comment by MarekMichali** [comment]
Unit test: #2570

**Comment by MarekMichali** [comment]
Docs: #2571
