### ISSUE TITLE
KEB CLI - support showing failed steps in the given service instances

### ISSUE THREAD

**Issue by PK85** [kyma-project/control-plane#2407]
**Description**

This is part of [Identify failed steps in KEB deprovisioning](https://github.com/kyma-project/control-plane/issues/2392)
This ticket is about the kcp CLI implementation in the KEB component.

**AC**
- [x] 1) kcp cli prints steps which needs retry.
- [x] 2) Find out a way how to see what steps failed for removed service instances (Those ones that are marked for retry)
- [x] 3) Check if kcp rt ... do not show deleted ones.
- [x] 4) Check --events feature for --only-deleted if it needs adjustment or not

**Comment by wozniakjan** [comment]
> ￼ 3) Check if kcp rt ... do not show deleted ones.

currently still not applicable, I will keep monitoring progress on https://github.com/kyma-project/control-plane/issues/2406

**Comment by wozniakjan** [comment]
small regression discovered, fix pending in https://github.com/kyma-project/control-plane/pull/2471. Other scenarios should be ok.
