### ISSUE TITLE
Add integration test for BTP Manager secret reconciliation

### ISSUE THREAD

**Issue by PK85** [kyma-project/control-plane#2496]
**Description**

E2E test about BTP Manager secret reconciliation by KEB. Implementation of that feature [here](https://github.com/kyma-project/control-plane/issues/2495).

**AC**
- [x] 1) Provision SKR on DEV environment with testing BTP Operator credentials.
- [x] 2) Assert if a secret for BTP Manager is created and data equals point 1.
- [x] 3) Simulate secret deletion in the SKR. Awaits till the secret is reconciled back to the proper one.
- [x] 4) Simulate secret values change in the SKR. This will be not reverted by KEB.

**Comment by PK85** [comment]
Right now we have only global reconciliation ON on DEV. Consider setting interval time on DEV for 5 minutes. Then all skr* tests will work as expected with up to 5 minutes time to get secret back.

**Comment by szwedm** [comment]
PR: https://github.com/kyma-project/kyma/pull/17600

**Comment by szwedm** [comment]
pjtester: https://github.com/kyma-project/test-infra/pull/7799
test runs in prow: https://status.build.kyma-project.io/?job=szwedm_test_of_prowjob_skr-aws-integration-dev
