### ISSUE TITLE
List all cleanup changes we need to apply to KEB when we will work with Lifecycle Manager only

### ISSUE THREAD

**Issue by PK85** [kyma-project/control-plane#2498]
**Description**

Soon or later all modules will be supported only via Lifecycle Manager. This ticket is about preparing a list of tasks that we need to remove from KEB code, e.g. overrides, kyma version etc

**AC**
- [x] 1) Find all features in the KEB that will be abandoned when we will use Lifecycle Manager only
- [x] 2) Prepare tasks ready to be taken in the next sprints.

Timeboxed to Size/S.

**Comment by piotrmiskiewicz** [comment]
LM manager does not get any overrides, additional components and Kyma Version.

## Functionality, which could be removed

### Steps to remove (overrides and Reconciler):
1. Provisioning:
 - OverridesFromSecretsAndConfigStep (overrides)
 - BTPOperatorOverridesStep (overrides), note: check if cluster ID is needed
 - CreateClusterConfiguration (reconciler)
 - CheckClusterConfigurationStep  (reconciler)
2. Update:
 - BTPOperatorOverridesStep
 - ApplyReconcilerConfigurationStep
 - CheckReconcilerState
3. Deprovision
 - DeregisterClusterStep
 - CheckClusterDeregistration
4. Upgrade Kyma
 - BTPOperatorOverridesStep
 - OverridesFromSecretsAndConfigStep
 - ApplyClusterConfigurationStep
 - CheckClusterConfigurationStep

### Steps to modify:
provisioning/initialisation.go - remove disabling BTP component code

### Packages to remove
internal/runtimeoverrides
internal/version
internal/reconciler

### InputBuilderFactory cleanup, remove following items (and corresponding methods): optComponentsSvc, componentsProvider, disabledComponentsProvider

### RuntimeInput cleanup
1. Remove the following methods:
 - EnableOptionalComponent
 - DisableOptionalComponent
 - SetOverrides, AppendOverrides
 - AppendGlobalOverrides
 - CreateClusterConfiguration
2. Remove the following fields: overrides, globalOverrides, componentsDisabler, enabledOptionalComponents

**Comment by piotrmiskiewicz** [comment]
Tasks:
[ ] - Remove (or modify) unnecessary steps (listerd in the previous comment)
[ ] - Cleanup  RuntimeInput, InputBuilderFactory

**Comment by ralikio** [comment]
We are removing Kyma version completely.

**Comment by szwedm** [comment]
@piotrmiskiewicz nice summary, I went through the code and spotted pretty much the same places for changes/cleanup. If we drop Kyma versions then we can still prepare configurations per plan.
