### ISSUE TITLE
Adjust KEB queue/manager parameters

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/control-plane#2506]
KEB processes (provisioning, deprovisioning, update) uses queues (with operations waiting for processing) and a manager implementation which runs steps for given operations.
Currently, the number of workers are fixed (hardcoded) to 5, which is ok. The manager implementation does not return an item (operation) back to the queue if the step needs a retry. Instead, it has a `time.Sleep` which blocks the worker:
https://github.com/kyma-project/control-plane/blob/main/components/kyma-environment-broker/internal/process/staged_manager.go#L229

Currently, the worker is blocked to 10 minutes, then the item is sent back to queue, and the worker can take next one.
The problem may occur, when we have 40 deprovisioning requests. We can observe a rate limiting - 5 deprovisioning started per 10 minutes. 

The goal is to adjust it to have bigger throughput.

**AC:**
 - reduce time for processing one step without sending back to the queue.

Notes:
- observe whether other services (Provisioner, Gardener) can handle more requests when there are changes to worker pool and time limit for operation execution,
- use parameters per environments to adjust the worker pool and time limit,
- monitor metrics in Grafana.

**Comment by szwedm** [comment]
Issue should be recreated (if needed) in KEB repository: https://github.com/kyma-project/kyma-environment-broker. Closing.
