### ISSUE TITLE
Delete_Kyma_Resource step does not complete properly after suspension  

### ISSUE THREAD

**Issue by jaroslaw-pieszka** [kyma-project/control-plane#2507]
**Description**

In the scenario:
- provisioning
- suspension
- deprovisioning
Delete_Kyma_Resource step is ended prematurely without failure, so it is not completed and marked as logically deleted with non-empty list of not completed steps.

The reason is that we calculate name of resource to be deleted based on runtimeID and for suspended instances runtimeID is empty.

**Expected result**

In above-mentioned scenario we execute and complete the step.

**Actual result**

We log error and mark step as succeeded but not completed (step is added to `executedButNotCompleted` array.

**Steps to reproduce**
- provision
- suspend
- deprovision

**Comment by piotrmiskiewicz** [comment]
https://github.com/kyma-project/control-plane/pull/2513
