### ISSUE TITLE
KEB: soft delete SKR Service Instances and Service Bindings when subaccount deletion event sent to us

### ISSUE THREAD

**Issue by PK85** [kyma-project/control-plane#2512]
**Description**
When subaccount event arrives from BTP, KEB starts Kyma deprovisioning and  btp-operator fails to be uninstalled cause instances and bindings have finalizers. In such a scenario we need to soft delete instances and bindings.

**AC**
- [x] 1) Provide something like```kymaContext``` root element in the payload when KEB is called and put information that ```subaccountDeletion=true```. Then when it is present, do a soft delete. 
- [x] 2) Adjust subaccount deletion job to send such a kymaContext to KEB
- [x] 3) Describe in the KEB documentation this adjustment.

**Comment by wozniakjan** [comment]
> 1) Provide something likekymaContext root element in the payload when KEB is called and put information that subaccountDeletion=true. Then when it is present, do a soft delete.￼
> 2) Adjust subaccount deletion job to send such a kymaContext to KEB

the instance `DELETE` endpoint call is defined by OSB API. So it has fixed parameters and no payload body. But there appears to be `force` parameter defined by OSB API which is currently unused by KEB at all, so I would like to propose https://github.com/kyma-project/control-plane/pull/2514 using `DELETE` on `/instance/${instance_id}?force=true` for this case.

**Comment by PK85** [comment]
@wozniakjan lets discuss that solution tomorrow, maybe including maper as well

**Comment by wozniakjan** [comment]
@PK85 here is an alternative proposal using HTTP header to identify the caller: https://github.com/kyma-project/control-plane/pull/2520. I decided to go for `User-Agent` but am happy to change this to KEB special-purpose header if you think that would work better.
