### ISSUE TITLE
Invalid Cals to Non-idempotent AVS

### ISSUE THREAD

**Issue by ralikio** [kyma-project/control-plane#2518]
**Description**

Steps in KEB are designed to run multiple times. The step https://github.com/kyma-project/control-plane/blob/59dbec7826e8d48fcd948b6d31dd7cb7c2b7df38/components/kyma-environment-broker/internal/process/deprovisioning/avs_evaluations.go#L40 does not follow this conventions. Because of the compound "if" condition if any of AVSExternalEvaluationDeleted or AVSInternalEvaluationDeleted is not set because of additional logic or failure, then the whole process repeats calling non-idempotent AVS again.

**Comment by MarekMichali** [comment]
See #2519

Other scenarios, such as a lack of connection to the DB, should be checked to see if they cause the step to be false repeated.

**Comment by MarekMichali** [comment]
Upon further investigation, the original logic is correct, but requires some refactoring to clean up redundant code that is confusing. A separate ticket will be opened.
