### ISSUE TITLE
Expose global account ID and plan ID in KEB operation metrics

### ISSUE THREAD

**Issue by ebensom** [kyma-project/control-plane#252]
**Description**

Include the global account ID and service plan ID of the instance to corresponding provisioning and deprovisioning operation Prometheus  metrics. 

**Reasons**

Better traceability of clusters for prometheus alerts. 
Better prioritization of incident based on plan (e.g. for trial runtimes, there is no SLA and hence no support outside of business hours required).

**Attachments**

**Comment by polskikiel** [comment]
https://github.com/kyma-project/control-plane/pull/288
