### ISSUE TITLE
Consider moving k8s jobs to a single component

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/control-plane#253]
**Description**

Currently there are the following jobs in the Control Plane:
- Subscription clean up
- Sub account clean up 
- Environments clean up

Subscription clean up job source code is in a separate component whereas two others are part of Kyma Environment Broker source code. Consider moving all the jobs to a single component. 

**Reasons**

In order to make it easier to search in the code base we should store all the jobs in one place. We could use domain oriented approach and put all jobs in KEB.

**Possible solutions**
- move all jobs to KEB <- preferred as it makes dependency management easier
- make separate component for these jobs

**Comment by franpog859** [comment]
Except moving the job we need to also merge the internal libraries and adjust the prow jobs. Keep in mind that we should test it on DEV probably running these jobs manually
