### ISSUE TITLE
Degenerated clusters with no runtime_id and kyma namespace cannot be automatically deprovisioned

### ISSUE THREAD

**Issue by jaroslaw-pieszka** [kyma-project/control-plane#2663]
For some time we had missing config map for expected kyma version so we had a lot of failed provisions with error:
```
msg: "cannot create input creator for plan 361c511f-f939-4621-b228-d0fb79a1fe15: while getting configuration for given version and plan: while verifying configuration configmap existence: configmap with configuration does not exist"
```

However cluster metadata were created then deprovision process failed. 
Such clusters are attempted to be deprovisioned by `retrigger_deprovision_job` but due to some missing data to no avail.
Steps that are not completed are:

```json
          "executedButNotCompletedSteps": [
            "Release_Subscription",
            "Delete_Kubeconfig"
          ],
```

Relevant messages:
```
msg: "namespace for Kyma resource not specified"
```

```
after successful deprovisioning failing to release hyperscaler subscription - determine the type of hyperscaler to use for planID [361c511f-f939-4621-b228-d0fb79a1fe15]: cannot determine the type of Hyperscaler to use for cloud provider 
```

```
failed to delete kubeconfig secret /kubeconfig- for lifecycle manager: an empty namespace may not be set when a resource name is provided
```

These messages indicates that missing data are preventing removal.
- runtime_id
- hyperscaler
- namespace for Kyma resource

Example instance_ids:
- 78777ffe-faae-4e31-9798-730c530ede6d
- 7fe3499e-8682-4747-8514-49b7c66fd077

**Comment by szwedm** [comment]
`Delete_Kubeconfig` step fix: https://github.com/kyma-project/control-plane/pull/2957

**Comment by szwedm** [comment]
Release_Subscription step fix: https://github.com/kyma-project/control-plane/pull/2960

**Comment by szwedm** [comment]
Closing the issue since it has been addressed by provided PRs.
