### ISSUE TITLE
Remove obsolete KCP installation resources

### ISSUE THREAD

**Issue by szwedm** [kyma-project/control-plane#2693]
KCP installation procedure described in readme and [control-plane/installation](https://github.com/kyma-project/control-plane/tree/b57fcbdc2e7c5bdc1a7f35292cced3228a1cb2c9/installation) directory are long overdue. We should remove unsupported installation procedure to avoid confusion.

Related ProwJobs have been already removed:
https://github.com/kyma-project/test-infra/pull/7500

**Comment by szwedm** [comment]
PR: https://github.com/kyma-project/control-plane/pull/2694

**Comment by MarekMichali** [comment]
PR: https://github.com/kyma-project/test-infra/pull/7501
