### ISSUE TITLE
Clean-up of user data after instance removal

### ISSUE THREAD

**Issue by jaroslaw-pieszka** [kyma-project/control-plane#2705]
There was an investigation done in scope of https://github.com/kyma-project/control-plane/issues/2592

Prepare and implement solution taking into consideration findings and conclusions in above-mentioned issue.

AC:
- after defined retention period all operations referring to removed instance are deleted
- after defined retention period all runtime states referring to removed instance are deleted
- dry-run mode is implemented
- periodic job responsible for removal after retention period does not operate neither on `operations` nor on `runtime_states` tables

**Comment by szwedm** [comment]
Superseded by: https://github.com/kyma-project/kyma-environment-broker/issues/440
