### ISSUE TITLE
Prepere KEB to be ready when Kyma resource will have new version

### ISSUE THREAD

**Issue by PK85** [kyma-project/control-plane#2761]
We faced issues when the LM guys adjusted the version from alpha to beta.

**AC**
- [x] 1) Make sure that updating the template to the new version will be the only change required on KEB side

**Comment by piotrmiskiewicz** [comment]
PR: https://github.com/kyma-project/control-plane/pull/2891

**Comment by szwedm** [comment]
PR with images bumps:
https://github.com/kyma-project/control-plane/pull/2906
