### ISSUE TITLE
Fix Provisioner cluster role binding creation process

### ISSUE THREAD

**Issue by koala7659** [kyma-project/control-plane#2858]
This is a Follow Up story after fixing [issue 1912](https://github.com/kyma-project/control-plane/issues/1912):

**Description:**

Provisioner is responsible for initial setup of the created Kyma Runtime.

There was once [introduced functionality](https://github.com/kyma-project/control-plane/pull/799) to dynamically update list of runtime administrators by the Provisioner during Upgrade Shoot API call. This code was supposed to create and label  required `ClusterRoles` and `ClusterRoleBindings` to generate correct set of administrators accounts during creation/update of the managed Kyma Runtime. 

Code responsible for creating ClusterRoles and ClusterRole bindings can be found here:
https://github.com/kyma-project/control-plane/blob/main/components/provisioner/internal/operations/stages/provisioning/create_operators_bindings.go

**Problems with code:**

- Mixed responsibility - same step is evenly executed after creation of Kyma Runtime and when Gardener Shoot is updated. Expected results are different. This can be treated as of violation **Single Responsibility Principle**.
- Code does not works to handle correctly updates of list of SKR administrators. Bindings must be added manually by the first administrator when new administrators. It is not obvious for the user. It is possible that provisioner API is not called properly when the list of subaccount administrator is changed 
- Created ClusterRules are not labeled according to convention with label `reconciler.kyma-project.io/managed-by=reconciler`
- Code is not covered properly with Unit Tests

**Suggested solution:** 

1. Check with other teams what is the current state of functionality to update list of administrators of SKR with Provisioner.
2. Refactor the code.
   A. If Provisioner is not able to dynamically update runtime bindings - consider removing execution path for shoot upgrade.
   B. If Provisioner is somehow able to dynamically update runtime bindings - Consider refactoring of the code by splitting it into two separate operations executed on different stages of Kyma runtime
3. Add label `reconciler.kyma-project.io/managed-by=reconciler` for created `ClusterRules`
5. Cover code with unit tests

[Moved from Provisioner to KIM]

**Comment by tobiscr** [comment]
@koala7659 : could we keep this closed as the provision has reached End-Of-Life soon?

**Comment by koala7659** [comment]
@tobiscr I think we should close this. This code is being gradually removed (. https://github.com/kyma-project/control-plane/pull/3438/files) and soon will be fully replaced with new `infrastructure-manager` service
