### ISSUE TITLE
[Provisioner] Incorrect Azure shoot specification in networking section - NAT-Gateway public IPs got replaced

### ISSUE THREAD

**Issue by mvshao** [kyma-project/control-plane#2901]
**Description**

The Provisioner duplicates Shoot spec structs [here](https://github.com/kyma-project/control-plane/blob/main/components/provisioner/internal/model/infrastructure/azure/infrastructure.go) and this very old, outdated, invalid infrastructure config is used for [serializing API response from Gardener cluster](https://github.com/kyma-project/control-plane/blob/main/components/provisioner/internal/model/gardener_config.go#L470C2-L500)

[Slack thread linked with this issue](https://sap-btp.slack.com/archives/CQF0V9075/p1688410393415509)

**Expected result**

NAT-Gateway public IPs have not got replaced (static public IPs won't change after node pool change)

**Actual result**

NAT-Gateway public IPs got replaced
shoot--[name-for-shoot]-nat-gateway-2 -> shoot--[name-for-shoot]-nat-gateway-z2-ip

**Possible way to reproduce**
- scaling up a shoot on Azure with public ip having to name similar to shoot--[name-for-shoot]-nat-gateway-2
- NAT Gateway updates in Azure will be triggered
- Observe the outcome, new public ip with naming like shoot--kyma--[name-for-shoot]-nat-gateway-z2-ip could have been created and associated with NAT Gateway (instead of the existing IP).

**Troubleshooting**
We need information about what is needed to change, and what is the new correct network infrastructure specification. Maybe @ebensom and SRE team have this information and could help here.

**Comment by ebensom** [comment]
I would rather tríy to fix this and any possible future bugs similar like this by 

- either refactor the code to use `Patch()` on Shoot instead of `Update()` (which eliminates many potential problems) 
- or else rely on Gardener shoot API package instead of copied structs, so you get the API model updates by updating the gardener dependency.

**Comment by mvshao** [comment]
The problem was resolved by merging the #2920 fix. If the problem occurs in the future feel free to reopen this issue.
