### ISSUE TITLE
Provisioner - Extend Provisioning API to support IP ranges for pods and services networks

### ISSUE THREAD

**Issue by koala7659** [kyma-project/control-plane#2946]
**Description:**

There is a customer request to extend `ProvisionRuntime` API call with possibility to configure network plugin for created shoot cluster with IP address ranges for pods and services networks.

At the moment Provisioner configures the network plugin only with node network IP address range.  

Example networking configuration in Gardener shoot yaml: 

```yaml
spec: 
  ....
  networking:
    type: calico
    ....
    pods: 100.64.0.0/12
    nodes: 10.250.0.0/16
    services: 100.104.0.0/13
    ....
```

**Suggested implementation:**

New Provisioning parameters will be added to `ProvisionRuntime` mutation. They will be optional and will be passed by the KEB when user provides them in Kyma Runtime creation dialog. 
The GraphQL input contains `GardenerConfigInput` struct (part of `ClusterConfigInput` which is a part of `ProvisionRuntimeInput`) where input shoot parameters are stored .  

In GraphQL schema we will extend `GardenerConfigInput` [struct](https://github.com/kyma-project/control-plane/blob/6eab33fcaf32434530efc06ed267670b7458d549/components/provisioner/pkg/gqlschema/schema.graphql#L211) with two new optional fields: **podsNetworkCidr** and **srvNetworkCidr** :

```graphql
input GardenerConfigInput {
....
  podsNetworkCidr: String
  podsNetworkCidr: String 
  workerCidr: String!
...
}
```
  
If any of new parameters is specified - it will be applied to created shoot as part of its Networking configuration:

``` go
			Networking: &gardener_types.Networking{
				Type:  &networkingType, // Default value - we may consider adding it to API (if Hydroform will support it)
				Nodes: util.StringPtr(c.GardenerProviderConfig.NodeCIDR(c)),
				Services: util.StringPtrOrNil(c.GardenerProviderConfig.ServicesCIDR(c)),
				Pods: util.StringPtrOrNil(c.GardenerProviderConfig.PodsCIDR(c)),
			},
```

Database schema will have to be extended accordingly with new flelds.

We need also to extend `GardenerConfig` [struct](https://github.com/kyma-project/control-plane/blob/6eab33fcaf32434530efc06ed267670b7458d549/components/provisioner/pkg/gqlschema/schema.graphql#L9C11-L9C11) and fill it correctly in `RuntimeStatus` mutation. 

```graphql
input GardenerConfig {
....
  podsNetworkCidr: String
  podsNetworkCidr: String 
  workerCidr: String
...
}
```

**Reasons:**
This feature is needed to prevent IP address conflicts for migrated applications (like Industry Cloud) connecting to some hosts via networks with immutable IP addresses. These applications have very strict requirements for the range of used IP address. 

**Benefits:**
Impact on Kyma adoption 

**Attachments:**
- Issue for KEB: https://github.com/kyma-project/control-plane/issues/2942
- Original issue: some internal github /kyma/backlog/issues/4050

**Comment by piotrmiskiewicz** [comment]
@koala7659 please paste example of the GraphQL payloads - with IP ranges (new feature) and without the IP range (as it is now)

**Comment by Disper** [comment]
@piotrmiskiewicz [here](https://github.com/kyma-project/control-plane/blob/c726e1a738e6b3fcd1bafa214de9a292e7a26f06/components/provisioner/pkg/gqlschema/schema.graphql#L225-L226) you can see fields that were added, and also I'm attaching below requested payloads examples:

<details>
  <summary>Payload without IP ranges</summary>
  
  ``` graphql

mutation {
        provisionRuntime(
          config: {
            runtimeInput: {
              name: "md-aws-cidr9",
            },
            clusterConfig: {
              gardenerConfig: {
                name: "md-aws-cidr9"
                kubernetesVersion: "1.26.5"
                diskType: "gp2"
                volumeSizeGB: 50
                machineType: "m5.xlarge"
                provider: "aws"
                targetSecret: "gardener-secret"
                workerCidr: "10.254.0.0/16",
                region: "eu-central-1",
                autoScalerMin: 3
                autoScalerMax: 4
                maxSurge: 1
                maxUnavailable: 1
                providerSpecificConfig: {
                    awsConfig: { 
                        vpcCidr: "10.250.0.0/16", 
                        awsZones:[ {
                            name: "eu-central-1a", 
                            publicCidr: "10.250.32.0/20",
                            internalCidr: "10.250.48.0/20",
                            workerCidr: "10.250.0.0/19"
                        }
                        ]
                    } 
                }
              }
            }
          }
        )
        {
          runtimeID
          id
        }
      }
  ```
</details>

<details>
  <summary>Payload with IP ranges</summary>
  
  ``` graphql
mutation {
        provisionRuntime(
          config: {
            runtimeInput: {
              name: "md-aws-cidr9",
            },
            clusterConfig: {
              gardenerConfig: {
                name: "md-aws-cidr9"
                kubernetesVersion: "1.26.5"
                diskType: "gp2"
                volumeSizeGB: 50
                machineType: "m5.xlarge"
                provider: "aws"
                targetSecret: "gardener-secret"
                workerCidr: "10.254.0.0/16",
                podsCidr: "100.128.0.0/12",
                servicesCidr: "100.112.0.0/13",
                region: "eu-central-1",
                autoScalerMin: 3
                autoScalerMax: 4
                maxSurge: 1
                maxUnavailable: 1
                providerSpecificConfig: {
                    awsConfig: { 
                        vpcCidr: "10.250.0.0/16", 
                        awsZones:[ {
                            name: "eu-central-1a", 
                            publicCidr: "10.250.32.0/20",
                            internalCidr: "10.250.48.0/20",
                            workerCidr: "10.250.0.0/19"
                        }
                        ]
                    } 
                }
              }
            }
          }
        )
        {
          runtimeID
          id
        }
      }

  ```
</details>

**Comment by piotrmiskiewicz** [comment]
@Disper @akgalwas looks ok for me, just one question regarding workerCIDR - it is in the gardenerConfig (new field) and in the awsZones. Is it ok?

**Comment by pbochynski** [comment]
Please consider changing the default subnet mask from /16 to /25. The smaller subnet will make it easier to create VPC peering (peering requires not overlapping IP ranges). The network mask /25 allows creating clusters with 127 nodes and should be sufficient for our customers.

**Comment by Disper** [comment]
Support in provisioner was merged in https://github.com/kyma-project/control-plane/pull/2968.
There are a few additional things that have been discovered:
- [ ] Fix returning values of new field when they are not provided by the user
- [ ] extend additionally components/provisioner/internal/api/resolver_integration_test.go
- [ ] see if provisioned can report an issue back to KEB when cluster creation hangs due to an issue with Gardener 
- [ ] test full e2e flow with KEB

**Comment by Disper** [comment]
`podsCidr` and `servicesCidr` fields are available in Provisioner.
