### ISSUE TITLE
Mark kyma resource as internal

### ISSUE THREAD

**Issue by PK85** [kyma-project/control-plane#3005]
**Description**

Pass information from KEB into Lifecycle Manager `Kyma` resource about internal users.

**Reason**

Lifecycle Manager has the functionality to display in the SKR `internal` modules.

**AC**
- [x] 1) Set label when creating SKR
- [x] 2) Update label value when upgrading SKR

**Technical information**
- Kyma resource label: `operator.kyma-project.io/internal` set to true
- KEB has a piece of knowledge about internal usage by calculating `license` ers_context attribute

**Comment by MarekMichali** [comment]
PR: https://github.com/kyma-project/control-plane/pull/3021
