### ISSUE TITLE
KEB supports configuration for  AVS internal and external evaluations are both set to the maintenance mode or not

### ISSUE THREAD

**Issue by PK85** [kyma-project/control-plane#3008]
**Description**

We'd like to support ZDM (Zero Downtime Maintenance) in the Kyma Environment and for that we need to configure AVS in a proper way.

**Reason**

We cannot currently test ZDM cause AVS is always set to Maintenance Mode.

**AC**
- [x] 1) Allow configuring if AVS maintenance mode is set or not, global configuration per environment. 
  - [x] 1.1)  define a name for that property
  - [x] 1.2) set explicitly values for all envs
- [x] 2) Allow configuring AVS maintenance mode FALSE for given GA Ids.
  - [x] 2.1) define a name for that property, [example list we introduced in the past](https://github.tools.sap/kyma/management-plane-config/blob/main/resources/control-plane/prod/values.yaml#L483)
  - [x] 2.2) set explicitly values for all envs

**Links**
- See SRE ticket: https://github.tools.sap/kyma/backlog/issues/4252#issuecomment-3506402

**Comment by szwedm** [comment]
@ebensom the question is how often would you use a new param? If we aim for a default zero downtime maintenance then the new param will become obsolete rather quickly

**Comment by ebensom** [comment]
@PK85 @szwedm I think what we need is two things:
1. global configuration to disable the feature of setting / resetting AvS maintenance mode. This is needed because once kyma is ZDM we want to disable the whole feature globally and eventually even remove the whole feature code from KEB.
2. Selectively disable the feature during testing of ZDM. But now that I read PKs argument, I agree that it will be easier to remove the code if we just support selective disablement per GA / SA id using a Configmap. So I'M fine with the original proposal 👍

**Comment by szwedm** [comment]
@PK85 @ebensom After looking through the code I suggest to extend [the current avs config](https://github.com/kyma-project/control-plane/blob/e4967ed88c0da16a998a16296eba950f79a4bb96/resources/kcp/charts/kyma-environment-broker/values.yaml#L173) with a new object. The new object will contain info about maintenance setting and possible exceptions from the rule:
```yaml
avs:
  ...
  maintenance:
    enabled: true # true until ZDM is default
    exceptions: # list of GA IDs
```
We have three places where AvS evaluations statuses are set to maintenance:
https://github.com/kyma-project/control-plane/blob/e4967ed88c0da16a998a16296eba950f79a4bb96/components/kyma-environment-broker/internal/process/upgrade_cluster/initialisation.go#L160
https://github.com/kyma-project/control-plane/blob/e4967ed88c0da16a998a16296eba950f79a4bb96/components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go#L211
https://github.com/kyma-project/control-plane/blob/e4967ed88c0da16a998a16296eba950f79a4bb96/components/kyma-environment-broker/internal/process/upgrade_kyma/check_cluster_configuration.go#L72

I would like to keep maintenance status logic within AvS EvaluationManager as it contains config with all the required info:
https://github.com/kyma-project/control-plane/blob/e4967ed88c0da16a998a16296eba950f79a4bb96/components/kyma-environment-broker/internal/avs/evaluation_manager.go#L9

The flow will be rather simple. If AvS maintenance is enabled then set maintenance status for all evaluations except for the ones connected to GA IDs present in the `exceptions` list in the config. One question, is setting maintenance mode on GA IDs level enough or should we narrow it down to SA IDs?

**Comment by PK85** [comment]
maybe something like that:
```
avs:
  ...
  maintenance:
    disabled: false # false until SKR ZDM is done
    alwaysDisabledGlobalAccountIDs: # list of GA IDs where maintenance mode is disabled
```

**Comment by szwedm** [comment]
PR: https://github.com/kyma-project/control-plane/pull/3028
