### ISSUE TITLE
KEB trial cleanup supports cleaning up failed trial clusters

### ISSUE THREAD

**Issue by ebensom** [kyma-project/control-plane#3024]
**Description**

Besides managing the expiry of trial runtimes, KEB trial cleanup job should also automatically trigger deprovisioning of trial runtimes wich are in failed state from lifecycle management point of view, i.e. in failed provisioning/unsuspension or failed deprovisioning/suspension state.

**Reasons**

SRE has another automation to automatically perform trial cleanup of failed runtimes which we plan to deprecate as the goal overlaps with the KEB trial cleanup job. 

**Attachments**

**Comment by PK85** [comment]
As disussed that's fine that after two weeks, we will suspend all types of trials, that means including  failed provisioning/unsuspension or failed deprovisioning/suspension sceanrios.

**Comment by jaroslaw-pieszka** [comment]
After analysis (@PK85, @piotrmiskiewicz and @jaroslaw-pieszka) we concluded that we need touch above places:
1. https://github.com/kyma-project/control-plane/blob/aa836f723a31c05c3d7ce663106c87425fdebf3c/components/kyma-environment-broker/cmd/trialcleanup/main.go#L94C118-L95C1 - action item: job itself must take all instances regardless it is expired or not (this will allow to trigger expiration again for previous expirations that failed).
2. https://github.com/kyma-project/control-plane/blob/aa836f723a31c05c3d7ce663106c87425fdebf3c/components/kyma-environment-broker/internal/suspension/handler.go#L77C1-L78C1 - action item: we analyzed the code and it looks that it could handle previous expirations that failed. In addition if we adjust suspension from deprovisionings marked as temporary to all deprovisionings then we will handle even the scenario that user triggered deprovisioning and it failed.

**Comment by ebensom** [comment]
@PK85 @piotrmiskiewicz @jaroslaw-pieszka I think you don't be able to suspend all failed trial runtimes. 

- failed provisioning: -> runtime was not created successfully, call deprovision instead of suspension or marking expiry.
- failed deprovisioning -> runtime was to be deleted, call deprovision API again
- failed suspension: -> call suspension (instance update with active: false param) again 
- failed unsuspension: -> runtime was not recreated successfully during unsuspension. call suspension (instance update with active: false param) again

**Comment by szwedm** [comment]
@ebensom we have discussed the issue in the team and decided to prepare a temporary solution which will handle failed provisioning and failed deprovisioning scenarios. Suspension retriggers are already covered. See the PR I'm currently preparing: https://github.com/kyma-project/kyma-environment-broker/pull/66. In the long term, we want to have a new internal endpoint in KEB which will handle the expiration of instances. I will create a separate issue for the new endpoint.
