### ISSUE TITLE
Store `podsCidr` and `servicesCidr` in provisioner database

### ISSUE THREAD

**Issue by Disper** [kyma-project/control-plane#3038]
**Description**

[Based on this comment](https://github.com/kyma-project/control-plane/pull/2968#pullrequestreview-1593738233) - we should return values for new `podsCidr` and `servicesCidr` fields when they are not provided by the user and are assigned by the Gardener as we do for seed. All we need to do is to store them in the database just after the moment when the cluster was successfully created.
You can find the relevant example for seed in the [proceedToInstallation function](https://github.com/kyma-project/control-plane/blob/main/components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_creation.go#L91C1-L114C9) in the Provisioning process.

However, it was not urgent, as it was confirmed that KEB does not need them.

**Attachments**
Follow-up of https://github.com/kyma-project/control-plane/issues/2946.

**Comment by akgalwas** [comment]
Closing as this is not used by the KEB.
