### ISSUE TITLE
Provisioner returns information determining whether runtime is registered in Compass

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/control-plane#3085]
**Description**

Provisioner should return information that would allow KEB to determine whether runtime was registered in Compass.

**Reasons**
Compass Manager will take over Compass integration functionality at some point. In order to perform smooth migration, Provisioner needs to notify Kyma Environment Broker that particular runtime was registered in Compass. 

Additionally adding graceful unregistration of runtime.  Do not return error if runtime is already deleted from Compass

**Comment by akgalwas** [comment]
API proposal
```graphql
type OperationStatus {
    id: String
    operation: OperationType!
    state: OperationState!
    message: String
    runtimeID: String
    compassRuntimeID: String # new property
    lastError: LastError
}
```
`compassRuntimeID` will contain identifier returned by the Compass. If `OperationStatus` returned from `provisionRuntime`, `runtimeStatus`, or `runtimeOperationStatus` is empty it should be assumed that the runtime is not registered in Compass.

**Comment by akgalwas** [comment]
**Implementation notes**
There are two possible implementations:
1. Provisioner stores the information on registration status in the database. When Provisioner stops to register runtimes in Compass new runtimes will return values determining runtime is not registered. All the old runtimes will return values from the database.
2. Provisioner doesn't store any new data in the database. When provisioner stops to register runtimes in Compass for all runtimes return values determining runtime is not registered.

The first proposal is more consistent, but the second is easier to implement. The final decision should be based on the migration plan prepared for Compass Manager migration.

**Comment by mvshao** [comment]
We could also think about graceful deregistration of the Runtime in Provisioner. Kyma CR is removed earlier than triggering deprovisioning. CM will deregister the runtime faster than the Provisioner will.
Example:
user deletes runtime -> Kyma CR is first deleted -> Compass Manager catches event -> deregisters runtime from Compass -> KEB makes call deprovision -> Provisioner tries to delete runtime -> we get runtime notFound error

**Comment by koala7659** [comment]
@mvshao I think we can use Feature Flag to not enable deregistration of the runtime in Compass Manager until https://github.com/kyma-project/control-plane/issues/3088 is implemented

**Comment by mvshao** [comment]
The PR is now merged. Can this issue be closed?

**Comment by mvshao** [comment]
Closing as @koala7659 said that is done
