### ISSUE TITLE
Provisioning failing on k8s 1.27

### ISSUE THREAD

**Issue by Disper** [kyma-project/control-plane#3240]
**Description**
Since https://github.com/kyma-project/control-plane/pull/2932 we are always passing `spec.kubernetes.enableStaticTokenKubeconfig: true` flag. Which is no longer acceptable in Gardener for k8s 1.27.

**Expected result**

- [x] Provisioning should be successful for k8s 1.27 version.
- [x] Upgrading shoot from 1.26 to 1.27 should be successful

**Actual result**

Provisioning for k8s 1.27 version fails with:

```
{
  "errors": [
    {
      "message": "Failed to start provisioning, error creating Shoot for 5b419cc2-7701-45db-889c-9c46838324f7 cluster: %!!(MISSING)!(MISSING)s(MISSING), Shoot.core.gardener.cloud \"ff-md-im-rs\" is invalid: spec.kubernetes.enableStaticTokenKubeconfig: Invalid value: true: for Kubernetes versions \u003e= 1.27, enableStaticTokenKubeconfig field cannot not be set to true, please see https://github.com/gardener/gardener/blob/master/docs/usage/shoot_access.md#static-token-kubeconfig",
      "path": [
        "provisionRuntime"
      ],
      "extensions": {
        "error_code": 500,
        "error_component": "k8s client - gardener",
        "error_reason": "Invalid"
      }
    }
  ],
  "data": {
    "provisionRuntime": null
  }
}
```

**Steps to reproduce**

Running `provisionRuntime` mutation with `kubernetesVersion: "1.27.6"`.

**Blocks**
- https://github.com/kyma-project/control-plane/issues/3052

**Comment by Disper** [comment]
Should be fixed with https://github.com/kyma-project/control-plane/pull/3242

**Comment by Disper** [comment]
We had a sync with @kyma-project/gopher and it seems that the above fix will move the provisioning forward but some additional changes might be needed.

Acceptance criteria:
- [ ] test the fix using 1.27 that was updated using KEB's orchestration mutation 
- [ ] test that on a freshly provisioned cluster - @kyma-project/gopher support would be needed to be able to either pass k8s version parameter or have special KEBs instance/plan prepared.

**Comment by tobiscr** [comment]
Relates to https://github.com/kyma-project/control-plane/issues/3052

**Comment by Disper** [comment]
As discussed today with @piotrmiskiewicz and @akgalwas, we see a current plan as:
- [ ] @piotrmiskiewicz will verify if KEB supports static and dynamic kubeconfigs the same way (rest of the plan depends on it)
- [ ] @kyma-project/framefrog will apply fix in provisioner
- [ ] @kyma-project/framefrog will test whether upgrading a shoot from 1.26 to 1.27 works on DEV (the idea is either to use a feature flag, or test that using a separate provisioner deployment)
- [ ] are will perform the shoots upgrade on DEV (unblocks 1.27 upgrade on DEV)
- [ ] are will perform the shoots upgrade on STAGE (unblocks 1.27 upgrade on STAGE)
- [ ] are will perform the shoots upgrade on PROD (unblocks 1.27 upgrade on PROD)

**Comment by tobiscr** [comment]
@piotrmiskiewicz : could you please provide feedback whether the fix is working out (see checkbox 1 above). THX in advance!

**Comment by Disper** [comment]
Just talked with @piotrmiskiewicz and:
KEB will work fine with both dynamic and static kubeconfigs, but one important remark is that Infrastructure Manager **must be** enabled on a given landscape, for the e2e scenario to work properly. [There is also one enhancement in KEB but it's not blocking to this story](https://github.com/kyma-project/kyma-environment-broker/pull/321).

Otherwise, without Infrastructure-Manager KEB will still create a secret with a kubeconfig, but this kubeconfig will not be rotated (IM's responsibility) so LCM and reconciler would stop working after a few hours. The plan summary [in this comment](https://github.com/kyma-project/control-plane/issues/3240#issuecomment-1875268009) has been adjusted.
