### ISSUE TITLE
Subscription Cleanup Job in Provisioner

### ISSUE THREAD

**Issue by ralikio** [kyma-project/control-plane#3249]
**Description**

Some time ago Subscription Cleanup Job (SCJ) subcomponent has been moved to Kyma Environment Broker (https://github.com/kyma-project/control-plane/pull/1474). The reason might have been to keep components folder clean without "subcomponents" like SCJ on the same level as our main components. Because SCJ is not maintained by @kyma-project/gopher 
 and we discovered a requirement to keep only KEB related source code in our fresh KEB repository, the issue is about moving SCJ back to Control Plane repository.

**Comment by ralikio** [comment]
Draft PR: https://github.com/kyma-project/control-plane/pull/3248

**Comment by ralikio** [comment]
Together with @kyma-project/framefrog we decided to move Subscription Cleanup Job to new repository.

New repository: https://github.com/kyma-project/subscription-cleanup-job
PR with Owners files: https://github.com/kyma-project/subscription-cleanup-job/pull/1

**Comment by tobiscr** [comment]
During our daily today, we actually discussed the next steps and afaik it was NOT yet decided whether the code should go into a dedicated repo or into the lifecycle manager.

@PK85 : we are currently all busy with rollout and migration topics as we have several PROD rollouts this month. Why is this story pushed to be done without a previous alignment with us how the migration will be done?

We have in January no capacities available and would be really happy if we could interrupt this topic for now, agree how we technically want proceed with it, and continue in February.

**Comment by ralikio** [comment]
Hello @tobiscr! I disagree with your statement. I reached to Frog team to ask about your opinion on the subject. Especially, please remember thread about https://github.com/kyma-project/control-plane/pull/3248. The story started because we are refactoring our component. While doing so we do not force anyone to commit they sprint time on that story beside time needed to gather mentioned feedback. We volunteering to correct and work on issues that the team had.

**Comment by ralikio** [comment]
test-infra: https://github.com/kyma-project/test-infra/pull/9580

**Comment by ralikio** [comment]
Update with the new image: https://github.com/kyma-project/control-plane/pull/3264

**Comment by ralikio** [comment]
Removal from KEB: https://github.com/kyma-project/kyma-environment-broker/pull/313

**Comment by ralikio** [comment]
Done.
