### ISSUE TITLE
remove KMCs requirement to access gardener shoots

### ISSUE THREAD

**Issue by k15r** [kyma-project/control-plane#3312]
## Description

KMC gathers information about VPCs and LoadBalancer Configuration as well as IP CIDR ranges from gardener. As they are never used in the billing calculations we want to make these values optional in the schema for EDP. This will allow us to continue scraping clusters even if KMC cannot access the gardener cluster.

## Acceptance
- [x] [update](https://github.tools.sap/skydivingtunas/how-to/blob/master/kmc-edp/EDP%20details.md) the schema to make the network section optional 
- [x] update kmc to either not read information from gardener and omit the empty network section from data sent to edp
- [x] read all information that can be read from KEB (including ProviderType). This will allow us to remove gardener access
- [x] provider name returned from KEB for CCEE cluster is `sapconvergedcloud`, not `openstack`. Currently we use the value from the shoot config (`openstack`). This must be updated to work with the value returned from KEB (`sapconvergedcloud`).

**Comment by mfaizanse** [comment]
remember the provider name returned from KEB for CCEE cluster is `sapconvergedcloud`, not `openstack`.

**Comment by k15r** [comment]
some groundwork has been done [here](https://github.com/kyma-project/control-plane/pull/3324). Feel free to continue on that PR
