### ISSUE TITLE
Move KMC to its own repository

### ISSUE THREAD

**Issue by k15r** [kyma-project/control-plane#3327]
## Description

The control plane repository will be cleaned up in the future. To accomplish this we will have to move KMC to its own repository in the kyma-project organisation.

## Acceptance
- [x] create kyma-project/kyma-metrics-collector (based on template repository)
- [x] move all code from control-plane to the new repository keeping the commit history ([see](https://docs.github.com/en/get-started/using-git/splitting-a-subfolder-out-into-a-new-repository))
- [x] setup post-build jobs to work on the new repository
- [x] setup test pipelines as github actions
- [x] setup security scans on the new repository

**Comment by mfaizanse** [comment]
Checklist:
 - [ ] update codeowners
 - [ ] update gitignore

**Comment by k15r** [comment]
enable dependabot: https://github.com/kyma-project/kyma-metrics-collector/pull/14
