### ISSUE TITLE
Setup a release process for KMC

### ISSUE THREAD

**Issue by k15r** [kyma-project/control-plane#3330]
## Description

KMC is now hosted in its own repository #3327 . Setup a release process to release new versions of KMC and deploy them to the various landscapes.

## Acceptance

- [x] setup a release process for new KMC versions similar to [KEB](https://github.com/kyma-project/kyma-environment-broker/blob/main/.github/workflows/create-release.yaml), [doc](https://github.com/kyma-project/kyma-environment-broker/blob/main/docs/contributor/04-20-release.md)
  - releases follow semantic versioning
  - APP_VERSION in helm charts needs to match the released version 
  - **NOTE**: KMC helm chart is stored in management-plane-charts, not in upstream as in KEB.
- [x] release a new version of KMC based on the new release process
- [x] deploy the new version to stage and prod.
   - [x] dev
   - [x] stage
   - [x] prod

**Comment by mfaizanse** [comment]
## Checklist

- [ ] Change `create_scan_config.sh` to use `TAG`.
- [ ] Enable `Validate labels` step.
