### ISSUE TITLE
[CCEE] Remove limitation / whitelisting for CCEE regions from provisioner

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/control-plane#3381]
**Description**

Caused by #3294, we introduced a restriction of allowed CCEE regions to the provisioner. WE agreed with @kyma-project/gopher to remove this limitation from provisioner and to take the KEB as single point of truth which provides us this data pre-validated.

AC:
- [x] Provisoner is not limiting the region for CCEE and using the value provided by KEB without applying further checks

**Comment by mvshao** [comment]
Changes have been successfully propagated to environments (Dev, Stage, Prod)
