### ISSUE TITLE
create new KMC deployment setup following new management-plane-chart based approach

### ISSUE THREAD

**Issue by k15r** [kyma-project/control-plane#3400]
# Description

with KMC in its new dedicated repository we can create a new deployment setup following other components previously hosted in control-plane.

# Acceptance
- [x] update the deployment means to work with the new repository and operate in similar way as KEB and other management plane components
- [x] move also the dashboards from the `kcp-sap`-branch in the `management-plane-charts` repo to the new chart for kmc

**Comment by mfaizanse** [comment]
- KMC helm charts are migrated to `management-plane-charts`
- Promethues rules and dashboards have been also migrated.
- KMC to rolled out to all 3 landscapes.
