### ISSUE TITLE
Changing the administrator list of a Kyma clusters doesn't update the role-bindings accordingly

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/control-plane#3431]
**Description**

A change of the administrator list of a Kyma cluster (Gardener cluster) has to change the cluster-role bindings accordingly.

This modification is supported via the BTP cockpit. See also the [documentation in SAP Help portal](https://help.sap.com/docs/btp/sap-business-technology-platform/overwrite-kyma-administrators).

Steps to update the administrators of a Kyma Kubernetes cluster:

* Click on `Manage environment instance` in BTP cockpit
    
    ![image](https://github.com/kyma-project/infrastructure-manager/assets/73824711/fd619933-865d-4426-b2ff-428b1d582fd5)

* Navigate to `Environments` and select Kyma
* Click on `View current configuration` and edit the JSON and update the list of administrators
* Alternatively, edit in the wizard the field `Administrators`

     ![image](https://github.com/kyma-project/infrastructure-manager/assets/73824711/8e8fa140-5f60-4e74-a1b3-f2ad8da90857)

**Expected result**
Changes in the administrator list leads to adjusted `ClusterRoleBinding` resources in the Kyma Kubernetes cluster.

**Actual result**

Changing the adminstrator list ist not reflected in the available `ClusterRoleBinding`s.

**Steps to reproduce**

**Troubleshooting**

**Comment by PK85** [comment]
I talked to @marco-porru, he will ask customer to:
-  update administrator lists to one user, or
-  delete manually clusterRoleBindings

Closing.
