### ISSUE TITLE
[CCEE] Configure Auditlog for CCEE Australia region

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/control-plane#3437]
**Description**

We are extending Kyma in CCEE and will also support the Australian region in Q2 this year.

The configuration of th provisioner has to be adjusted to be aware about the Australia region and to set the Auditlog instance correctly.

AC:
- [ ] Provisioner supports Australia region and configured the corresponding Auditlog server correctly in Gardener

**Comment by tobiscr** [comment]
We aligned with @ebensom today that the Australia Auditlog instance will be created in calendar week 21/24.

**Comment by ebensom** [comment]
I think for CCEE Australia region, the existing AWS ap-southeast-2 audit log service instancces should be used:

- stage
    ```
          "ap-au-1": {
            "tenantID": "e3e6459a-2c6f-403c-94db-164cb9348a6c",
            "serviceURL": "https://api.auditlog.cf.ap10.hana.ondemand.com:8081",
            "secretName": "aws-audit-stage-ap-southeast-2"
          },

    ```
- prod
    ```
      "ap-au-1": {
        "tenantID": "ef25782b-7915-4cba-bdcb-cd81a7494ea3",
        "serviceURL": "https://api.auditlog.cf.ap10.hana.ondemand.com:8081",
        "secretName": "aws-audit-prod-ap-southeast-2"
      },
    ```

**Comment by tobiscr** [comment]
@mvshao : SREs are done with their work. We can go ahead and test it :)
