### ISSUE TITLE
Enable OIDC extension in Provisioner

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/control-plane#3466]
**Description**

The Gardener OIDC extension is important for several important customers of Kyma. Caused by some delays in the rollout of KIM, we decided to enable this extension already in the Provisioner to unblock our customers in their goals.

Related line is:

```
extensions:
   - type: shoot-oidc-service  #this line enables OIDC extension
```
We will enable this OIDC extension in all new created Gardener clusters. **Shoot-Specs of existing clusters will NOT be updated!**

AC:
- [ ] Enable GArdener's OIDC extension per default in all shoot-specs of new created clusters

Appendix:
* Gardener Docs: https://github.com/gardener/gardener-extension-shoot-oidc-service/blob/master/docs/usage/openidconnects.md

**Comment by abbi-gaurav** [comment]
Hi @tobiscr , is there some documentation added / planned in help.sap.com to let SKR users know how they can use it?

**Comment by tobiscr** [comment]
This is actually not the official feature we want to deliver. We enabled the OIDC extension in Provisioner only because we had customers who were blocked in their go-live. 

The official feature is https://github.com/kyma-project/kyma/issues/18305. But we need first to migrate KIM on Production and also KEB has to make additional OIDC-providers configurable via BTP cockpit.

The documentation will happen for the the feature is fully supported.
