### ISSUE TITLE
KEB operations refactor - get rid of unmarshaling ProvisioningParameters

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/control-plane#365]
**Description**

AC:
 - get rid of unmarshaling ProvisioningParameters when it is needed
 - the changes must be applied in Provisioning/Deprovisioning/Upgrade operations
 - get rid of GetProvisioningParameters which returns error. Think about having provisioning parameters as private field so developer is unable to modify it.

see: https://github.com/kyma-project/control-plane/pull/364

Raw estimation - 3 MD:
- 1 day for design and prepare 3 operation models (Provisioning/Deprovisioning/UpgradeKyma)
- 1 day for all changes (it is about 42 usages of the method)
- 1 day for a review

**Comment by polskikiel** [comment]
already fixed with parameters migration
