### ISSUE TITLE
Deprovisioning queue never finishes

### ISSUE THREAD

**Issue by polskikiel** [kyma-project/control-plane#414]
**Description**

Operation on error is updated what causes refresh of `UpdatedAt` time which prevents timeouts because of our if expression:

```
if time.Since(operation.UpdatedAt) > CheckStatusTimeout { ... }
```

imo we should consider to take `CreatedAt` time into account rather than `UpdatedAt`.

The situation is the same in the other queues

**Expected result**

Operation fails after timeout

**Actual result**

Operation is stuck in the never ending loop

**Comment by klaudiagrz** [comment]
Fixed in this PR:
https://github.com/kyma-project/control-plane/pull/415
