### ISSUE TITLE
HAP returning subscriptions to the pool

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/control-plane#42]
**Description**

In order to reduce the number of subscriptions being used for creating clusters and remove old, assigned ones, we would like to have a functionality that will return empty subscriptions back to the pool for reusing them in the future. After the last cluster in the subscription is removed it should be unassigned from the given tenant and returned back to the pool of subscriptions that are available for the new tenants to provision their clusters.

**Acceptance Criteria**

- After the last cluster in the subscription is removed it should be unassigned from the tenant who used it before
- Unassigned subscriptions are available for new tenants who want to provision a cluster

**Comment by janmedrek** [comment]
Another thing to note - we would need to also make sure that the subscriptions are completely empty when unassigning them from a previous tenant.

**Comment by pbochynski** [comment]
@janmedrek Did you accept the story? Can you close it?
