### ISSUE TITLE
Kyma environment broker schema errors

### ISSUE THREAD

**Issue by andreaAlkalay** [kyma-project/control-plane#421]
Hi,

We have noticed an issue with the kyma create plan schema (exposed via /v2/catalog endpoint)
``` 
"zones": {
        "items": [
          {
            "type": "string"
          }
        ],
        "type": "array"
      }
``` 
Where it should be:
``` 
 "zones": {
        "items": {
            "type": "string"
          },
        "type": "array"
      }
```
Since we are now working on a generic form to support the kyma provisioning we are expecting to have a valid json schema structure.

Best Regards,
Andrea.

**Comment by PK85** [comment]
Closing, Zones parameter will be not available in the schema.
