### ISSUE TITLE
Refactor storage tests in KEB

### ISSUE THREAD

**Issue by polskikiel** [kyma-project/control-plane#428]
**Description**

What can be done:

- split storage_test.go to separate files so e.g. 
   - `operation_test.go`
   - `instance_test.go`
   - `lmsTenant_test.go`
   - ...
- place above tests in a separate package // maybe `internal/storage/driver/postsql` is a good place for this kind of tests
- fulfil every structures' fields with a test data and assert if it was propagated through the storage
- fixtures can be moved to the separate place `fixtures.go` 
- think about splitting tests to a smaller parts - test only the particular functions without having something like e2e storage test for operations

**AC**
- Tests covers all scenarios, more assertions etc
- Developer can run single test (without commenting out other tests etc)
- No single monolith test file 
- Decrease test execution from 2 min to 30 seconds

**Comment by ksputo** [comment]
Suggestion: we could move fixtures next to the model in code, instead of creating separate fixtures in each place where for example `Instance` is needed

**Comment by szwedm** [comment]
Proposed changes have been implemented. Closing.
