### ISSUE TITLE
Metris gather metrics from gardener and kyma-cluster directly

### ISSUE THREAD

**Issue by k15r** [kyma-project/control-plane#430]
**Description**

Metris is a component to gather billing related information for multiple clusters spun up on gardener, and sending it to other systems (EDP). Currently it only supports scraping metrics of clusters running on Azure. As gardener can also be spin up clusters on AWS, metris needs to be enhanced to support clusters running on AWS.

The information collected by metris for every cluster should adhere to the schema defined [here](https://github.com/kyma-project/control-plane/blob/master/components/metris/README.md).
Information about event_hubs can be omitted, as SKR will drop usage of event_hubs.

**Reason**
SKR is currently supported only on Azure, but in the future we will support spinning up SKRs on other hyperscalers. With the current implementation it every new supported hyperscaler would require a change to metris. 

As there is no additional value added by querying the hyperscaler directly, skipping this step will ease maintenance of metris as well as speed up the process of supporting kyma on more platforms.

**Acceptance criteria**
- [x] get virtual machine information from gardener shoot spec
  * map from machine type to provisioned cpu / memory
- [x] get storage information from the shoot cluster and the shoot spec directly
  * shoot spec contains the system disks
  * the cluster contains PVs for other storage means
- [x] network related data can be gathered from the cluster directly
- [x] In addition to these changes we need to check if KEB can be used to provide metris with the list of currently existing runtimes by leveraging the `info/runtimes` endpoint. 
- [x] As KEB and metris work in the same context (control plane) one single source for mapping supported machine types (Standard_D4_v3 => 4CPU / 16GB Memory ... ) shall be established
- [x] changes to the metris/EDP schema are accepted by edp.

**Comment by sayanh** [comment]
Further enhancement issue: https://github.com/kyma-project/control-plane/issues/512
