### ISSUE TITLE
Provisioner must not allow to upgrade hibernated cluster

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/control-plane#458]
**Description**

hibernateRuntime query allows to hibernate cluster. Once a cluster is hibernated it makes sense to either wake it up or remove. Current implementation allows to execute upgradeRuntime and upgradeShoot on hibernated cluster.

**Expected result**

upgradeRuntime and upgradeShoot should return error without starting upgrade operation.

**Actual result**

Upgrade operation starts and timeouts after some time.

**Comment by janmedrek** [comment]
Provisioner will be transferred to the Reconciler framework
