### ISSUE TITLE
Alerting for metris

### ISSUE THREAD

**Issue by k15r** [kyma-project/control-plane#491]
**Description**

Expose metrics for metris and create alerting rules based on those metrics

**Reason**

The metris component allows to gather billing relevant data of all created runtimes. Getting up-to-date usage statistics for those runtime is crucial for correct billing. In order to ensure correct reporting we need to implement alerting mechanisms that trigger on-call incidents in case data is missing, or clusters cannot be scraped.

**AC**

- [x] per cluster report statistics (error rate, number of continuous errors since last success)
- [x] general statistics (number of overall errors since last success)(think: [RED](https://www.weave.works/blog/the-red-method-key-metrics-for-microservices-architecture/))
- [x] number clusters scraped (plus rate change)
- [x] Alerts configured based on those metrics
- [x] Add Tests for metrics

- KEB is used to configure subaccounts on EDP (which subaccounts should be tracked). Alerts for failures in this functionality need to be provided as well -> moved to #818

**Comment by k15r** [comment]
https://github.tools.sap/kyma/backlog/issues/1105

**Comment by grischperl** [comment]
https://github.com/kyma-incubator/metris/pull/3

**Comment by grischperl** [comment]
Alerts for KEB configure sub accounts was moved to separate issue: #818
