### ISSUE TITLE
KEB retries saving upgrade operation in Create_Runtime step in case of conflict

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/control-plane#499]
**Description**

In case of a conflict (because of optimistick locking) KEB does not saves the operation in the CreateRuntime step. This may result with provisioning a cluster but do not save any ID of such runtime.
After that we have an orphaned SKR.

AC:
 - saving the operation in the CreateRuntime step should be retried in case of a conflict
 - this should be covered by a unit test

**Comment by polskikiel** [comment]
PR: https://github.com/kyma-project/control-plane/pull/549
