### ISSUE TITLE
Improve the KCP overview on the home page for KCP docs

### ISSUE THREAD

**Issue by majakurcius** [kyma-project/control-plane#573]
**Description**

Extend and improve the overview of KCP on the [home page for KCP documentation](https://kyma-project.io/docs/control-plane/) to make it more informative and more inviting to "newcomers".

**Area**

* KCP - documentation

**Reasons**

The home page for KCP documentation on the Kyma website contains very little information on what KCP really is. If someone doesn't already know it, it's not informative at all. 
Also, with just 2 sentences, it looks very poor and uninviting.

**Assignees**

@kyma-project/technical-writers

**Attachments**

![image](https://user-images.githubusercontent.com/53601578/110114977-b5f1b000-7db5-11eb-98bb-41d640d06555.png)

**Comment by majakurcius** [comment]
This shall be invalidated with #676.

**Comment by PK85** [comment]
@majakurcius closing then, if needed reopen
