### ISSUE TITLE
KEB disables components according to Kyma version

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/control-plane#577]
**Description**

KEB needs to provide a component list to provision synchronized with Kyma version. 
AC:
 - KEB allows to be configured with different component lists for different versions.

**Reasons**

The Kyma 1.21 changes the eventing engine. We need to disable "knative" and enable "nats" component. 

**Attachments**

**Comment by radufa** [comment]
**- For Kyma 1.20 (component name / namespace):**

 stage and prod:  
       - kantive-eventing / knative-eventing
       - knative-eventing-kafka / knative-eventing
       - event-sources / kyma-system
       
 trial:
       - kantive-eventing / knative-eventing
       - knative-provisioner-natss / knative-eventing
       - nats-streaming / natss
       - event-sources / kyma-system

**- For Kyma 1.21, without Knative, feature flag "IsEMSDisabled = true", automatically upgrade from Kyma 1.20:**

trial, stage and prod:
      - eventing / kyma-system
     
**- For Kyma 1.22 (could change):**
stage and prod with feature flag "IsEMSDisabled = false"
      - eventing / kyma-system 

trial with feature flag "IsEMSDisabled = true"     
     - eventing / kyma-system

**Comment by piotrmiskiewicz** [comment]
for 1.21 we need to see: ```func NewDisabledComponentsProvider() DisabledComponentsProvider {
	return map[string]map[string]struct{}{
		broker.AllPlansSelector: {
			components.Backup:                  {},
			components.BackupInit:              {},
			components.KnativeEventing:         {},
			components.KnativeEventingKafka:    {},
			components.KnativeProvisionerNatss: {},
			components.NatsStreaming:           {},
		},
		broker.OpenStackPlanID: {},
		broker.GCPPlanID:       {},
		broker.AzurePlanID:     {},
		broker.AzureLitePlanID: {},
		broker.AWSPlanID:       {},
		broker.TrialPlanID:     {},
	}
}```

**Comment by jasiu001** [comment]
KEB fetches component list per Kyma version from below links:
```
https://storage.googleapis.com/kyma-prow-artifacts/%s/kyma-installer-cluster.yaml
https://storage.googleapis.com/kyma-development-artifacts/%s/kyma-installer-cluster.yaml
```
if the component doesn't exist for the specific Kyma version then is not necessary to remove it from the list in KEB.

**Comment by piotrmiskiewicz** [comment]
let's do not change the disabled components list. The only problem would be for going to 1.20 and GCP plan, which is acceptable.
