### ISSUE TITLE
Fix, if necessary the curent interpretation of Kyma versions defined like: "1.20.0-rc4"

### ISSUE THREAD

**Issue by radufa** [kyma-project/control-plane#596]
1.20.0-rc4 is not 1.21

_Originally posted by @piotrmiskiewicz in https://github.com/kyma-project/control-plane/pull/572#discussion_r594915117_

**Comment by radufa** [comment]
Current implementation is if its a non semver version of kyma sent (eg. master-xxx or PR-xx or 1.20.0-rc4) then the error is ignored and assumed to be latest version

**Comment by piotrmiskiewicz** [comment]
no longer needed
