### ISSUE TITLE
KEB - implementation of new component list and overrides

### ISSUE THREAD

**Issue by jasiu001** [kyma-project/control-plane#600]
**Description**

One of the first job of KEB is to collect the all-components list of Kyma. There is a special provider for this (it is also used when other than the default Kyma version is used to collect components list for a specific version).
Old components provider based on artifacts with `Installation` resource (CR), now new Kyma installer based on a new list of components.
The component provider has to be adjusted to a new list of components for the new Kyma installation.

**Reasons**

Installation Kyma with a new approach of installation wouldn't be work with the old list of components.

**AC**
- [ ] KEB takes components.yaml and then pass configurations per component to reconciler (KEB do not pass URLs, reconciler know from where to get kyma charts)
- [ ] KEB has additionalComponens.yaml - we pass to reconcilder URLs too (+ credentials too)
- [ ] Overrides values.yaml file is taken by reconciler, KEB do not use that file at all. KEB configuration has top prio, then values.yaml then chart.yaml

**Info**
- overrides values.yaml vs profiles, less prio to high prio:
  1) chart
  2) profile
  3) overrides values.yaml
  4) KEB (overrides everything)
- kyma runtime part
  - components.yaml - https://github.com/kyma-project/kyma/blob/main/installation/resources/components.yaml
  - overrides.yaml - https://github.com/kyma-project/kyma/blob/main/installation/resources/values.yaml

**Comment by szwedm** [comment]
To proceed further with the implementation of this task we need a way to determine Kyma's major version. This major version should be accurate even for custom Kyma version. With correct major version in place we can proceed with the reading new components list and still support the old way for compatibility.
[PR for determining Kyma major version](https://github.com/kyma-project/control-plane/pull/914)

**Comment by PK85** [comment]
Accepted, will be presented with whole preview epic
