### ISSUE TITLE
Integration test for Kyma metrics collector

### ISSUE THREAD

**Issue by sayanh** [kyma-project/control-plane#613]
**Description**

Right now there are no integration tests for Kyma metrics collector which will ensure that it can scrape a running Kyma cluster and send metrics to some test namespace of event data platform. The aim of this issue to have such tests whenever there is a change in the charts for Kyma metrics collector.

**Reasons**

Ensure quality standards.

**Scenario**
- [ ] skr (A)  registered to KEB
- [ ] kmc scrapes A 
- [ ] metrics sent to edp dev

**Comment by sayanh** [comment]
My idea is to add another step in pre-main-control-plane-gke-integration to test the functionality of KMC.
WIP PRs:
https://github.com/kyma-project/test-infra/pull/4534
https://github.com/kyma-project/control-plane/pull/1176

I discarded the original plan of "Integration with spinnaker" cause the feedback will be too late for a developer(as Spinnaker jobs are executed once a PR is merged to main) whereas having it in "pre-main-control-plane-gke-integration" will make sure we test KMC along with other components of the control-plane on every change in "resources" folder.

**Comment by raypinto** [comment]
Current state:
There is a skeleton in test-infra to execute the job. 

Todo:
- [ ] Implement integration test for KMC

**Comment by VladislavPaskar** [comment]
@FriedrichWilken would you please share you findings ?
