### ISSUE TITLE
Refactor initialisation step and don't rerun steps that were executed without failure

### ISSUE THREAD

**Issue by PK85** [kyma-project/control-plane#622]
**Description**

This ticket is a part of [Make KEB well-organized](https://github.com/kyma-project/control-plane/issues/621).

**Reasons**

See [reasons](https://github.com/kyma-project/control-plane/issues/621).

**AC**

- refactor initialisation step
- don't rerun steps that were executed without failure
- before merging that enhancement, [THIS](https://github.com/kyma-project/control-plane/issues/619) one must be already in

**Comment by piotrmiskiewicz** [comment]
InputCreator must be persisted as other parts of the operation. Sensitive data must be encrypted (overrides).

**Comment by piotrmiskiewicz** [comment]
Tasks:
1. Persist the state of an InputCreator (and load the data from the database)
2. Do not rerun steps which succeeded
3. reorganize and split initialization step

**Comment by piotrmiskiewicz** [comment]
All steps are grouped into a stage. When all steps in a stage are succeeded - the stage is finished and will never be retried.  This feature allows us to define steps like:
 Stage "preparation": Initialisation (, AVS, LMS, CLS, Create_Runtime
 Stage "check provisioner": CheckProvisionerStatus (new step which only checks the provisioning status)
 Stage "posta actions": TagsForRuntime, AvS_External

**Comment by piotrmiskiewicz** [comment]
Status:
- [x]  Manager with stages
- [x]  Manager does not rerun finished stage
- [ ]  Manager does not rerun the queue
- [ ] Simplify (split) Initialisation
- [ ] Redefine a list of steps
- [ ] In case of a retry manager finds all other steps with the same weight and run it
