### ISSUE TITLE
Alerts for KEB configure subaccount functionality

### ISSUE THREAD

**Issue by grischperl** [kyma-project/control-plane#818]
**Background**
KMC reports billing data. Alerts have been configured in case functionality stops working. However, KEB talks independently to EDP to configure subaccounts (which subaccounts should be tracked). 

 **AC**
Alerts for failures in this functionality need to be provided as well.

**Comment by PK85** [comment]
@grischperl what kind of alert do u expect KEB should thrown and when?

**Comment by k15r** [comment]
@PK85 imho it should just be transparent if KEB EDP setup fails for a new instance. On KMC we expose a metric for the number of errors when communicating with EDP. An alert is configured if that number rises abnormally (https://github.com/kyma-project/control-plane/blob/main/resources/kcp/charts/kyma-metrics-collector/prometheus/alerts.yaml)
