### ISSUE TITLE
Update the KEB Swagger UI to be in sync with the KEB image

### ISSUE THREAD

**Issue by radufa** [kyma-project/control-plane#819]
**Description**

To avoid as much as possible the  direct communication between developers not familiar with KEB source and the KEB devs, the Swagger UI exposed by a KEB instance (using port-forward) could be the first "entry point" to be used.
It could be great to always have it in "sync" with the used KEB version. 

**Area**

**Reasons**

**Assignees**

@kyma-project/technical-writers

**Attachments**

**Comment by PK85** [comment]
@radufa what is not in sync?
