### ISSUE TITLE
Default zone for freemium cluster provisioning is wrong

### ISSUE THREAD

**Issue by berkanercan** [kyma-project/control-plane#840]
**Description**
The following provisioning failure indicates wrong zone name is used for cluster. 

`{"level":"error","msg":"Error from process: call to the provisioner service failed","operationID":"0865ca2c-5e62-47ae-b836-ff2db153954a","time":"2021-07-13T06:56:33Z"}
{"instanceID":"CA72E7FC-1B30-4231-9655-F38B663DC27F","level":"error","msg":"Process operation failed: call to the provisioner service failed","operation":"0865ca2c-5e62-47ae-b836-ff2db153954a","planID":"b1a5764e-2ea1-4f95-94c0-2b4538b37b55","provisioning":"manager","stage":"create_runtime","step":"Create_Runtime","time":"2021-07-13T06:56:33Z"}
{"instanceID":"CA72E7FC-1B30-4231-9655-F38B663DC27F","level":"error","msg":"call to Provisioner failed: failed to provision a Runtime: graphql: Failed to start provisioning, error creating Shoot for 0996249b-e0e0-48b8-8b43-ca5970fae4bb cluster: %!!(MISSING)!(MISSING)s(MISSING), shoots.core.gardener.cloud \"c-9954cd6\" is forbidden: [spec.provider.workers[0].zones[0]: Unsupported value: \"eu-central-1a\": supported values: \"eu-west-2a\", \"eu-west-2b\", \"eu-west-2c\"]","operation":"0865ca2c-5e62-47ae-b836-ff2db153954a","planID":"b1a5764e-2ea1-4f95-94c0-2b4538b37b55","provisioning":"manager","stage":"create_runtime","step":"Create_Runtime","time":"2021-07-13T06:56:33Z"}`

https://sap-btp.slack.com/archives/CSR4HDWEL/p1626159428039800

**Steps to reproduce**

Create a freemium cluster on gardener staging.
**Troubleshooting**

Upon investigation, we found out that the default zone name, which is defined [here](https://github.com/kyma-project/control-plane/blob/f6b50fd772bdba7c6794e130ace634f51335ad8e/components/kyma-environment-broker/internal/provider/aws_provider.go#L57), is not overwritten.

One suitable place to do that change is here: 
https://github.com/kyma-project/control-plane/blob/main/components/kyma-environment-broker/internal/process/input/input.go#L238

**Comment by PK85** [comment]
fixed
