### ISSUE TITLE
Add structured logging for KMC

### ISSUE THREAD

**Issue by sayanh** [kyma-project/control-plane#847]
**Description**

Add structured logging for KMC for better debugging.

**Comment by k15r** [comment]
Required definitions:
- which keys/values should go into the logging context

Maintain a set of guidelines for our logging approach

**Comment by marcobebway** [comment]
Requirements:
- Standardize logger context key/value pairs for the whole code-base (needed for doing grep/filter on the logs).
- Put suitable log level (DEBUG, INFO, ...) per log message.
- Standardise log messages in a way to be short and yet meaningful.

> Hint: Here is an example of a structured logger we use in the Eventing reconciler: https://github.com/kyma-incubator/reconciler/blob/main/pkg/reconciler/instances/eventing/log/log.go.

**Comment by k15r** [comment]
The recommended log output structure can be seen here: https://github.com/kyma-project/community/blob/main/concepts/observability-consistent-logging/improvement-of-log-messages-usability.md
