### ISSUE TITLE
Refactor Shoot provisioning to use queues mechanism follow-up

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/control-plane#85]
**Description**

There are the following topics to address: 
- We changed logic of provisioning in such a way that one of the stages (ShootProvisioning) is no longer valid. We added some logic on component startup that updates the database to allow correct operation resumption. The code will no longer make sense once all existing InProgress operations are updated.
- We refactored the Shoot controller in such an away that it is responsible for audit logs only. As a result, we can create a separate test for the controller and remove controller startup from resolver_integration_with_gardener_test.go 

**Reasons**

As a result, we will get rid of useless code and simplify resolver_integration_with_gardener_test.go

**Comment by rafalpotempa** [comment]
We don't have code related to that any more. We will clean up the codebase in https://github.com/kyma-project/control-plane/issues/922

**Comment by Disper** [comment]
No longer valid due to the new reconciler implementation.
