### ISSUE TITLE
Error messages in Provisioner may leak implementation details

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/control-plane#86]
**Description**

Error messages returned to the user are built by wrapping errors from internal components (database handling code, Hydroform/Terraform)  so that they can leak some implementation details. 

DB driver should be excluded from error message building mechanisms. We could use a more user-friendly message.
Consider making a split to:

- client errors
- internal errors

**Expected result**

An error message should not contain implementation details and be descriptive to the user. 

**Actual result**

Messages include errors returned from database driver or Terraform. 

**Steps to reproduce**

Call runtimeOperationStatus query with an id that is not a valid UUID. The result will be as follows:
```log
Failed to get <id> operation: pq: invalid input syntax for type uuid: <id>
```

In this case, the message should tell the user that they passed incorrect values. Instead, it says that the Postgres database driver returned an error.

**Comment by koala7659** [comment]
Proposal: To fix this bug we can migrate provisioner to use unified logging library as we did it in Application Validator https://github.com/kyma-project/kyma/pull/10315
