### ISSUE TITLE
Add possibility to create clusters without installing Kyma in Provisioner

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/control-plane#876]
**Description**

With the Reconciler taking over the responsibility of installing Kyma on provisioned clusters we need to add possibility to provision clusters without installation of Kyma.

**Reasons**

We need to prepare to Reconciler's takeover of Kyma installation.

**Acceptance Criteria**
- [ ] KymaConfig is optional in Provisioning mutation. Not passing it results in finishing operation without installing Kyma.
- [ ] API updated
- [ ] Documentation updated
- [ ] De-provisioning should work as expected

**Comment by majakurcius** [comment]
Provisioner schema will change (the Kyma installation part will be removed), therefore the documentation will need to be updated (provisioning and upgrade tutorials).

**Comment by franpog859** [comment]
This is a great opportunity to bring the Provisioner's integration tests back. We can clean up the flaky long-running tests that provision clusters, install Kyma, uninstall it and delete the cluster and convert them to non-installation operations! There are already pipelines ready for it. Check the existing pipelines, clean them up, and convert them to the non-installation flow 🎉

**Comment by franpog859** [comment]
Provisioner will be removed soon
