### ISSUE TITLE
Remove unused code from Runtime Provisioner

### ISSUE THREAD

**Issue by rafalpotempa** [kyma-project/control-plane#922]
**Description**

We have to remove stale, unused code related to the `ProviderSpecificConfig` and `ShootProvisioning`, e.g., https://github.com/kyma-project/control-plane/blob/main/components/provisioner/internal/provisioning/persistence/dbsession/factory.go#L51-L53

**Reasons**

We need to maintain code consistency and cut off unused parts.

**Acceptance Criteria**
- [ ] resolve all TODOs in Runtime Provisioner codebase

**Comment by Disper** [comment]
No longer valid due to the new reconciler implementation.
